// Lista de referência do Catálogo Nacional de Cursos Técnicos (CNCT),
// 4ª edição (MEC/Setec, Resolução CNE/CEB nº 2/2020, atualizado 22/10/2025).
// Sugestão (autocomplete) ao cadastrar curso técnico — não trava nada, a
// escola pode digitar nome/código diferente. `cbo` = Classificação Brasileira
// de Ocupações associada pelo catálogo (nulo quando o catálogo não define uma,
// ou em raros casos onde a extração automática do PDF não capturou o código).

export interface CursoTecnicoCNCT {
  nome: string;
  cbo: string | null;
}

export const CURSOS_TECNICOS_POR_EIXO: Record<string, CursoTecnicoCNCT[]> = {
  ambiente_saude: [
    { nome: "Técnico em Agente Comunitário de Saúde", cbo: "3222-55" },
    { nome: "Técnico em Análises Clínicas", cbo: "3242-05" },
    { nome: "Técnico em Citopatologia", cbo: "3242-15" },
    { nome: "Técnico em Controle Ambiental", cbo: "3115-05" },
    { nome: "Técnico em Cuidados de Idosos", cbo: "5162-10" },
    { nome: "Técnico em Dependência Química", cbo: "5153-15" },
    { nome: "Técnico em Enfermagem", cbo: "3222-05" },
    { nome: "Técnico em Equipamentos Biomédicos", cbo: "9153-05" },
    { nome: "Técnico em Estética", cbo: "3221-30" },
    { nome: "Técnico em Farmácia", cbo: "3251-15" },
    { nome: "Técnico em Gerência em Saúde", cbo: null },
    { nome: "Técnico em Hemoterapia", cbo: "3242-20" },
    { nome: "Técnico em Imagem Pessoal", cbo: null },
    { nome: "Técnico em Imobilizações Ortopédicas", cbo: "3226-05" },
    { nome: "Técnico em Massoterapia", cbo: "3221-20" },
    { nome: "Técnico em Meio Ambiente", cbo: null },
    { nome: "Técnico em Meteorologia", cbo: "3115-10" },
    { nome: "Técnico em Necropsia", cbo: "3281-05" },
    { nome: "Técnico em Nutrição e Dietética", cbo: "3252-10" },
    { nome: "Técnico em Optometria", cbo: "3223-05" },
    { nome: "Técnico em Podologia", cbo: "3221-10" },
    { nome: "Técnico em Prótese Dentária", cbo: "3224-10" },
    { nome: "Técnico em Radiologia", cbo: "3241-15" },
    { nome: "Técnico em Reciclagem", cbo: null },
    { nome: "Técnico em Registros e Informações em Saúde", cbo: null },
    { nome: "Técnico em Saúde Bucal", cbo: "3224-05" },
    { nome: "Técnico em Terapias Holísticas", cbo: "3221-25" },
    { nome: "Técnico em Veterinária", cbo: "5193-05" },
    { nome: "Técnico em Vigilância em Saúde", cbo: "3522-10" },
    { nome: "Técnico em Óptica", cbo: "3223-05" },
    { nome: "Técnico em Órteses e Próteses", cbo: "3225-05" },
  ],
  controle_processos_industriais: [
    { nome: "Técnico em Automação Industrial", cbo: "3001-05" },
    { nome: "Técnico em Eletroeletrônica", cbo: "3003-05" },
    { nome: "Técnico em Eletromecânica", cbo: "3003-05" },
    { nome: "Técnico em Eletrotécnica", cbo: "3131-05" },
    { nome: "Técnico em Eletrônica", cbo: "3132-05" },
    { nome: "Técnico em Fabricação Mecânica", cbo: "3142-05" },
    { nome: "Técnico em Ferramentaria", cbo: "7211-05" },
    { nome: "Técnico em Fundição", cbo: "3147-15" },
    { nome: "Técnico em Instrumentação Industrial", cbo: "3134-10" },
    { nome: "Técnico em Manutenção Aeronáutica em Aviônicos", cbo: null },
    { nome: "Técnico em Manutenção Aeronáutica em Célula", cbo: null },
    { nome: "Técnico em Manutenção Aeronáutica em Grupo Motopropulsor", cbo: null },
    { nome: "Técnico em Manutenção Automotiva", cbo: "3143-05" },
    { nome: "Técnico em Manutenção de Máquinas Industriais", cbo: null },
    { nome: "Técnico em Manutenção de Máquinas Navais", cbo: null },
    { nome: "Técnico em Manutenção de Máquinas Pesadas", cbo: null },
    { nome: "Técnico em Manutenção de Sistemas Metroferroviários", cbo: null },
    { nome: "Técnico em Mecatrônica", cbo: "3001-05" },
    { nome: "Técnico em Mecânica", cbo: "3141-10" },
    { nome: "Técnico em Mecânica de Precisão", cbo: "3141-05" },
    { nome: "Técnico em Metalurgia", cbo: "3146-20" },
    { nome: "Técnico em Metrologia", cbo: "3134-05" },
    { nome: "Técnico em Refrigeração e Climatização", cbo: "7257-05" },
    { nome: "Técnico em Sistemas a Gás", cbo: "7241-15" },
    { nome: "Técnico em Sistemas de Energia Renovável", cbo: null },
    { nome: "Técnico em Soldagem", cbo: "3146-20" },
  ],
  desenvolvimento_educacional_social: [
    { nome: "Técnico em Alimentação Escolar", cbo: "8414-08" },
    { nome: "Técnico em Arquivo", cbo: null },
    { nome: "Técnico em Biblioteconomia", cbo: "3711-10" },
    { nome: "Técnico em Brinquedoteca", cbo: null },
    { nome: "Técnico em Desenvolvimento Comunitário", cbo: null },
    { nome: "Técnico em Infraestrutura Escolar", cbo: "5143-25" },
    { nome: "Técnico em Laboratório de Ciências da Natureza", cbo: null },
    { nome: "Técnico em Multimeios Didáticos", cbo: null },
    { nome: "Técnico em Produção de Materiais Didáticos Bilíngues em Libras/Língua Portuguesa", cbo: null },
    { nome: "Técnico em Secretaria Escolar", cbo: "3515-05" },
    { nome: "Técnico em Tradução e Interpretação de Libras", cbo: null },
    { nome: "Técnico em Treinamento e Instrução de Cães-Guias", cbo: null },
  ],
  gestao_negocios: [
    { nome: "Técnico em Administração", cbo: "3513-05" },
    { nome: "Técnico em Comércio", cbo: "1414-05" },
    { nome: "Técnico em Comércio Exterior", cbo: "3513-10" },
    { nome: "Técnico em Condomínio", cbo: "5101-10" },
    { nome: "Técnico em Contabilidade", cbo: "3511-05" },
    { nome: "Técnico em Cooperativismo", cbo: null },
    { nome: "Técnico em Finanças", cbo: "3532-05" },
    { nome: "Técnico em Logística", cbo: "3911-25" },
    { nome: "Técnico em Marketing", cbo: "3541-40" },
    { nome: "Técnico em Qualidade", cbo: "3912-05" },
    { nome: "Técnico em Recursos Humanos", cbo: "3513-15" },
    { nome: "Técnico em Secretariado", cbo: "3515-05" },
    { nome: "Técnico em Seguros", cbo: "3517-35" },
    { nome: "Técnico em Serviços Jurídicos", cbo: "3514-30" },
    { nome: "Técnico em Serviços Públicos", cbo: null },
    { nome: "Técnico em Transações Imobiliárias", cbo: "3546-05" },
    { nome: "Técnico em Vendas", cbo: "3541-40" },
  ],
  informacao_comunicacao: [
    { nome: "Técnico em Computação Gráfica", cbo: null },
    { nome: "Técnico em Desenvolvimento de Sistemas", cbo: null },
    { nome: "Técnico em Informática", cbo: null },
    { nome: "Técnico em Informática para Internet", cbo: "3171-10" },
    { nome: "Técnico em Manutenção e Suporte em Informática", cbo: null },
    { nome: "Técnico em Programação de Jogos Digitais", cbo: null },
    { nome: "Técnico em Redes de Computadores", cbo: "3132-20" },
    { nome: "Técnico em Telecomunicações", cbo: "3133-15" },
  ],
  infraestrutura: [
    { nome: "Técnico Aeroportuário", cbo: "3425-20" },
    { nome: "Técnico em Agrimensura", cbo: "3123-05" },
    { nome: "Técnico em Carpintaria", cbo: "3212-05" },
    { nome: "Técnico em Desenho de Construção Civil", cbo: "3180-05" },
    { nome: "Técnico em Edificações", cbo: "3121-05" },
    { nome: "Técnico em Estradas", cbo: "3122-05" },
    { nome: "Técnico em Geodésia e Cartografia", cbo: "3123-05" },
    { nome: "Técnico em Geoprocessamento", cbo: "3123-20" },
    { nome: "Técnico em Hidrologia", cbo: "3123-15" },
    { nome: "Técnico em Portos", cbo: "3422-10" },
    { nome: "Técnico em Saneamento", cbo: "3122-10" },
    { nome: "Técnico em Transporte Aquaviário", cbo: "3426-10" },
    { nome: "Técnico em Transporte Metroferroviário", cbo: null },
    { nome: "Técnico em Transporte Rodoviário", cbo: "3422-10" },
    { nome: "Técnico em Transporte de Cargas", cbo: "3423-05" },
    { nome: "Técnico em Trânsito", cbo: "3423-05" },
  ],
  militar: [
    { nome: "Técnico em Bombeiro Aeronáutico", cbo: "5171-05" },
    { nome: "Técnico em Comunicações Aeronáuticas", cbo: "3133-10" },
    { nome: "Técnico em Comunicações Navais", cbo: null },
    { nome: "Técnico em Controle de Tráfego Aéreo", cbo: "3425-05" },
    { nome: "Técnico em Desenho Militar", cbo: "3185-10" },
    { nome: "Técnico em Eletricidade e Instrumentos Aeronáuticos", cbo: null },
    { nome: "Técnico em Equipamentos de Voo", cbo: "5173-10" },
    { nome: "Técnico em Estrutura e Pintura de Aeronaves", cbo: null },
    { nome: "Técnico em Fotointeligência", cbo: "3123-10" },
    { nome: "Técnico em Guarda e Segurança", cbo: "5173-10" },
    { nome: "Técnico em Hidrografia", cbo: "3123-15" },
    { nome: "Técnico em Informações Aeronáuticas", cbo: "5173-10" },
    { nome: "Técnico em Manobras e Equipamentos de Convés", cbo: null },
    { nome: "Técnico em Material Bélico", cbo: "9502-05" },
    { nome: "Técnico em Mecânica de Aeronaves", cbo: "3143-10" },
    { nome: "Técnico em Mergulho", cbo: null },
    { nome: "Técnico em Operação de Radar", cbo: null },
    { nome: "Técnico em Operação de Sonar", cbo: null },
    { nome: "Técnico em Operações de Engenharia Militar", cbo: null },
    { nome: "Técnico em Preparação Física e Desportiva Militar", cbo: null },
    { nome: "Técnico em Sensores de Aviação", cbo: null },
    { nome: "Técnico em Sinais Navais", cbo: null },
    { nome: "Técnico em Sinalização Náutica", cbo: null },
    { nome: "Técnico em Suprimento", cbo: "3911-15" },
  ],
  producao_alimenticia: [
    { nome: "Técnico em Agroindústria", cbo: "8181-10" },
    { nome: "Técnico em Alimentos", cbo: "3252-05" },
    { nome: "Técnico em Cervejaria", cbo: "8417-10" },
    { nome: "Técnico em Confeitaria", cbo: "8483-10" },
    { nome: "Técnico em Panificação", cbo: "8483-05" },
    { nome: "Técnico em Viticultura e Enologia", cbo: "3250-05" },
  ],
  producao_cultural_design: [
    { nome: "Técnico em Artes Circenses", cbo: "3762-15" },
    { nome: "Técnico em Artes Visuais", cbo: null },
    { nome: "Técnico em Artesanato", cbo: "7521-05" },
    { nome: "Técnico em Canto", cbo: null },
    { nome: "Técnico em Cenografia", cbo: "3742-05" },
    { nome: "Técnico em Composição e Arranjo", cbo: null },
    { nome: "Técnico em Conservação e Restauro", cbo: "7687-10" },
    { nome: "Técnico em Dança", cbo: "3761-05" },
    { nome: "Técnico em Design Gráfico", cbo: "3713-05" },
    { nome: "Técnico em Design de Calçados", cbo: "3188-15" },
    { nome: "Técnico em Design de Embalagens", cbo: "3184-30" },
    { nome: "Técnico em Design de Interiores", cbo: "3751-05" },
    { nome: "Técnico em Design de Joias", cbo: "7911-20" },
    { nome: "Técnico em Design de Moda", cbo: null },
    { nome: "Técnico em Design de Móveis", cbo: "3184-25" },
    { nome: "Técnico em Estilismo e Coordenação de Moda", cbo: null },
    { nome: "Técnico em Fabricação de Instrumentos Musicais", cbo: null },
    { nome: "Técnico em Figurino Cênico", cbo: "3188-10" },
    { nome: "Técnico em Instrumento Musical", cbo: null },
    { nome: "Técnico em Modelagem do Vestuário", cbo: "3188-10" },
    { nome: "Técnico em Multimídia", cbo: "3171-20" },
    { nome: "Técnico em Museologia", cbo: "3712-10" },
    { nome: "Técnico em Paisagismo", cbo: null },
    { nome: "Técnico em Processos Fotográficos", cbo: null },
    { nome: "Técnico em Produção Cultural", cbo: null },
    { nome: "Técnico em Produção de Moda", cbo: "3751-10" },
    { nome: "Técnico em Produção de Áudio e Vídeo", cbo: "3721-15" },
    { nome: "Técnico em Publicidade", cbo: null },
    { nome: "Técnico em Regência", cbo: null },
    { nome: "Técnico em Rádio e Televisão", cbo: "3732-15" },
    { nome: "Técnico em Teatro", cbo: "3742-05" },
  ],
  producao_industrial: [
    { nome: "Técnico em Açúcar e Álcool", cbo: "3111-05" },
    { nome: "Técnico em Biocombustíveis", cbo: null },
    { nome: "Técnico em Biotecnologia", cbo: "3253-05" },
    { nome: "Técnico em Calçados", cbo: "3191-05" },
    { nome: "Técnico em Celulose e Papel", cbo: "3111-10" },
    { nome: "Técnico em Cerâmica", cbo: "7523-05" },
    { nome: "Técnico em Construção Naval", cbo: "3182-15" },
    { nome: "Técnico em Curtimento", cbo: "3111-15" },
    { nome: "Técnico em Joalheria", cbo: null },
    { nome: "Técnico em Móveis", cbo: "3184-25" },
    { nome: "Técnico em Petroquímica", cbo: "3112-05" },
    { nome: "Técnico em Petróleo e Gás", cbo: "3011-15" },
    { nome: "Técnico em Planejamento e Controle da Produção", cbo: null },
    { nome: "Técnico em Plásticos", cbo: "3114-10" },
    { nome: "Técnico em Processamento da Madeira", cbo: "3212-05" },
    { nome: "Técnico em Processos Gráficos", cbo: "3713-10" },
    { nome: "Técnico em Química", cbo: "3111-05" },
    { nome: "Técnico em Têxtil", cbo: "3116-10" },
    { nome: "Técnico em Vestuário", cbo: "3191-10" },
    { nome: "Técnico em Vidros", cbo: "3113-05" },
  ],
  recursos_naturais: [
    { nome: "Técnico em Agricultura", cbo: "3211-05" },
    { nome: "Técnico em Agroecologia", cbo: "3211-05" },
    { nome: "Técnico em Agronegócio", cbo: null },
    { nome: "Técnico em Agropecuária", cbo: "3211-10" },
    { nome: "Técnico em Apicultura", cbo: "6134-05" },
    { nome: "Técnico em Aquicultura", cbo: "3213-05" },
    { nome: "Técnico em Cafeicultura", cbo: "3211-05" },
    { nome: "Técnico em Florestas", cbo: "3212-10" },
    { nome: "Técnico em Fruticultura", cbo: "3211-05" },
    { nome: "Técnico em Geologia", cbo: "3161-05" },
    { nome: "Técnico em Mineração", cbo: "3163-05" },
    { nome: "Técnico em Pesca", cbo: "3412-20" },
    { nome: "Técnico em Recursos Pesqueiros", cbo: "3213-05" },
    { nome: "Técnico em Zootecnia", cbo: "3231-05" },
  ],
  seguranca: [
    { nome: "Técnico em Defesa Civil", cbo: "3516-05" },
    { nome: "Técnico em Prevenção e Combate a Incêndio", cbo: null },
    { nome: "Técnico em Segurança do Trabalho", cbo: "3516-05" },
  ],
  turismo_hospitalidade_lazer: [
    { nome: "Técnico em Agenciamento de Viagem", cbo: "3548-10" },
    { nome: "Técnico em Eventos", cbo: "3548-20" },
    { nome: "Técnico em Gastronomia", cbo: "5132-05" },
    { nome: "Técnico em Guia de Turismo", cbo: "5114-05" },
    { nome: "Técnico em Hospedagem", cbo: "4221-20" },
    { nome: "Técnico em Lazer", cbo: "3714-10" },
    { nome: "Técnico em Serviços de Restaurante e Bar", cbo: null },
  ],
};