// Matrizes curriculares oficiais da SEED-PR (Instrução Normativa Conjunta
// relacionada às Resoluções SEED nº 84/2024 e 85/2024 — Matrizes Curriculares
// 2025, Ensino Regular e PEI). Fonte: documento oficial fornecido pela escola.
//
// Usado para pré-preencher automaticamente uma Matriz Curricular ao criar uma
// nova série/ano — a coordenação escolhe a modalidade, e todas as disciplinas
// com a carga horária semanal oficial são adicionadas de uma vez.

export type CategoriaMatrizOficial = "BNC" | "PD" | "FGB" | "PFO" | "IFA" | "IF";

export interface ItemMatrizOficial {
  nome: string;
  categoria: CategoriaMatrizOficial;
  cargaHorariaSemanal: number;
}

export interface SerieMatrizOficial {
  serieAno: string;
  itens: ItemMatrizOficial[];
}

export interface MatrizOficialTemplate {
  id: string;
  label: string;
  nivel: "fundamental" | "medio";
  series: SerieMatrizOficial[];
}

export const MATRIZES_OFICIAIS_SEED_PR: MatrizOficialTemplate[] = [
  {
    id: "fund_iniciais_tempo_parcial",
    label: "Ensino Fundamental - Anos Iniciais - Tempo Parcial",
    nivel: "fundamental",
    series: [
      {
        serieAno: "1º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 10 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 8 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "Língua Inglesa", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Convivência", categoria: "PD", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "2º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 10 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 8 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "Língua Inglesa", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Convivência", categoria: "PD", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "3º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 10 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 8 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "Língua Inglesa", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Convivência", categoria: "PD", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "4º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 10 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 8 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "Língua Inglesa", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Convivência", categoria: "PD", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "5º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 10 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 8 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "Língua Inglesa", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Convivência", categoria: "PD", cargaHorariaSemanal: 2 },
        ],
      },
    ],
  },
  {
    id: "fund_finais_tempo_parcial_diurno",
    label: "Ensino Fundamental - Anos Finais - Tempo Parcial Diurno",
    nivel: "fundamental",
    series: [
      {
        serieAno: "6º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 4 },
          { nome: "Língua Inglesa", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 5 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Tecnologia e Inovação", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Educação Financeira", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Redação e Leitura", categoria: "PD", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "7º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 4 },
          { nome: "Língua Inglesa", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 5 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Tecnologia e Inovação", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Educação Financeira", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Redação e Leitura", categoria: "PD", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "8º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 4 },
          { nome: "Língua Inglesa", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 5 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 4 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "Projeto de Vida", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Tecnologia e Inovação", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Educação Financeira", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Redação e Leitura", categoria: "PD", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "9º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 4 },
          { nome: "Língua Inglesa", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 5 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 4 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "Projeto de Vida", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Oe Matemática", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Oe Língua Portuguesa", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Redação e Leitura", categoria: "PD", cargaHorariaSemanal: 2 },
        ],
      },
    ],
  },
  {
    id: "fund_finais_tempo_parcial_noturno",
    label: "Ensino Fundamental - Anos Finais - Tempo Parcial Noturno",
    nivel: "fundamental",
    series: [
      {
        serieAno: "6º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 6 },
          { nome: "Língua Inglesa", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 6 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 3 },
        ],
      },
      {
        serieAno: "7º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 6 },
          { nome: "Língua Inglesa", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 6 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 3 },
        ],
      },
      {
        serieAno: "8º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 6 },
          { nome: "Língua Inglesa", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 6 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 3 },
        ],
      },
      {
        serieAno: "9º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 6 },
          { nome: "Língua Inglesa", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 6 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 3 },
        ],
      },
    ],
  },
  {
    id: "medio_tempo_parcial_diurno_matcnt",
    label: "Ensino Médio - Tempo Parcial Diurno - Itinerário Matemática e Ciências da Natureza",
    nivel: "medio",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Inglês", categoria: "IF", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 1 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Empreendedorismo", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Programação", categoria: "IF", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 1 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Oe Matemática", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Oe Língua Portuguesa", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Empreendedorismo", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Programação", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Biotecnologia", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Química Aplicada", categoria: "IF", cargaHorariaSemanal: 2 },
        ],
      },
    ],
  },
  {
    id: "medio_tempo_parcial_diurno_lggchs",
    label: "Ensino Médio - Tempo Parcial Diurno - Itinerário Linguagens e Ciências Humanas",
    nivel: "medio",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Inglês", categoria: "IF", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 1 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Liderança", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Oratória", categoria: "IF", cargaHorariaSemanal: 1 },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 1 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Oe Matemática", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Oe Língua Portuguesa", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Arte e Mídias Digitais", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Oratória", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Geopolítica", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Filosofia e Sociedade Moderna", categoria: "IF", cargaHorariaSemanal: 2 },
        ],
      },
    ],
  },
  {
    id: "medio_tempo_parcial_noturno_matcnt",
    label: "Ensino Médio - Tempo Parcial Noturno - Itinerário Matemática e Ciências da Natureza",
    nivel: "medio",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "IF", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 1 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Empreendedorismo", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Programação", categoria: "IF", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 1 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Oe Matemática", categoria: "IF", cargaHorariaSemanal: 3 },
          { nome: "Oe Língua Portuguesa", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Empreendedorismo", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Programação", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Biotecnologia", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Química Aplicada", categoria: "IF", cargaHorariaSemanal: 2 },
        ],
      },
    ],
  },
  {
    id: "medio_tempo_parcial_noturno_lggchs",
    label: "Ensino Médio - Tempo Parcial Noturno - Itinerário Linguagens e Ciências Humanas",
    nivel: "medio",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "IF", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 1 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Liderança", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Oratória", categoria: "IF", cargaHorariaSemanal: 1 },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 1 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Oe Matemática", categoria: "IF", cargaHorariaSemanal: 3 },
          { nome: "Oe Língua Portuguesa", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Arte e Mídias Digitais", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Oratória", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Geopolítica", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Filosofia e Sociedade Moderna", categoria: "IF", cargaHorariaSemanal: 2 },
        ],
      },
    ],
  },
  {
    id: "pei_fund_iniciais_9h",
    label: "PEI - Ensino Fundamental Anos Iniciais - 9H",
    nivel: "fundamental",
    series: [
      {
        serieAno: "1º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 10 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 8 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "Língua Inglesa", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Convivência", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Linguagens Artísticas", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Cultura do Movimento", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Práticas Experimentais", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Orientação de Estudos", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Assembleia", categoria: "PD", cargaHorariaSemanal: 1 },
        ],
      },
      {
        serieAno: "2º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 10 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 8 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "Língua Inglesa", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Convivência", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Linguagens Artísticas", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Cultura do Movimento", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Práticas Experimentais", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Orientação de Estudos", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Assembleia", categoria: "PD", cargaHorariaSemanal: 1 },
        ],
      },
      {
        serieAno: "3º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 10 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 8 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "Língua Inglesa", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Convivência", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Linguagens Artísticas", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Cultura do Movimento", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Práticas Experimentais", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Orientação de Estudos", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Assembleia", categoria: "PD", cargaHorariaSemanal: 1 },
        ],
      },
      {
        serieAno: "4º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 10 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 8 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "Língua Inglesa", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Convivência", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Linguagens Artísticas", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Cultura do Movimento", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Práticas Experimentais", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Orientação de Estudos", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Assembleia", categoria: "PD", cargaHorariaSemanal: 1 },
        ],
      },
      {
        serieAno: "5º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 10 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 8 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "Língua Inglesa", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Convivência", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Linguagens Artísticas", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Cultura do Movimento", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Práticas Experimentais", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Orientação de Estudos", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Assembleia", categoria: "PD", cargaHorariaSemanal: 1 },
        ],
      },
    ],
  },
  {
    id: "pei_fund_finais_7h",
    label: "PEI - Ensino Fundamental Anos Finais - 7H",
    nivel: "fundamental",
    series: [
      {
        serieAno: "6º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 4 },
          { nome: "Língua Inglesa", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 5 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "Projeto de Vida", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Oe Matemática", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Oe Língua Portuguesa", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Tecnologia e Inovação", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Educação Financeira", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Redação e Leitura", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Eletiva", categoria: "PD", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "7º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 4 },
          { nome: "Língua Inglesa", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 5 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "Projeto de Vida", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Oe Matemática", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Oe Língua Portuguesa", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Tecnologia e Inovação", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Educação Financeira", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Redação e Leitura", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Eletiva", categoria: "PD", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "8º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 4 },
          { nome: "Língua Inglesa", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 5 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 4 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "Projeto de Vida", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Oe Matemática", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Oe Língua Portuguesa", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Tecnologia e Inovação", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Educação Financeira", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Redação e Leitura", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Eletiva", categoria: "PD", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "9º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 4 },
          { nome: "Língua Inglesa", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 5 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 4 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "Projeto de Vida", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Oe Matemática", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Oe Língua Portuguesa", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Tecnologia e Inovação", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Redação e Leitura", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Eletiva", categoria: "PD", cargaHorariaSemanal: 2 },
        ],
      },
    ],
  },
  {
    id: "pei_fund_finais_9h",
    label: "PEI - Ensino Fundamental Anos Finais - 9H",
    nivel: "fundamental",
    series: [
      {
        serieAno: "6º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 4 },
          { nome: "Língua Inglesa", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 5 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "Projeto de Vida", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Oe Matemática", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Oe Língua Portuguesa", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Tecnologia e Inovação", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Educação Financeira", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Redação e Leitura", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Eletiva", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Robótica", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Práticas Experimentais", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Esporte-música-arte", categoria: "PD", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "7º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 4 },
          { nome: "Língua Inglesa", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 5 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "Projeto de Vida", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Oe Matemática", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Oe Língua Portuguesa", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Tecnologia e Inovação", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Educação Financeira", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Redação e Leitura", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Eletiva", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Robótica", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Práticas Experimentais", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Esporte-música-arte", categoria: "PD", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "8º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 4 },
          { nome: "Língua Inglesa", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 5 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 4 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "Projeto de Vida", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Oe Matemática", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Oe Língua Portuguesa", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Tecnologia e Inovação", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Educação Financeira", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Redação e Leitura", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Eletiva", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Robótica", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Práticas Experimentais", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Esporte-música-arte", categoria: "PD", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "9º Ano",
        itens: [
          { nome: "Língua Portuguesa", categoria: "BNC", cargaHorariaSemanal: 4 },
          { nome: "Língua Inglesa", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "BNC", cargaHorariaSemanal: 1 },
          { nome: "Educação Física", categoria: "BNC", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "BNC", cargaHorariaSemanal: 5 },
          { nome: "Ciências", categoria: "BNC", cargaHorariaSemanal: 4 },
          { nome: "Geografia", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "História", categoria: "BNC", cargaHorariaSemanal: 3 },
          { nome: "Projeto de Vida", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Oe Matemática", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Oe Língua Portuguesa", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Tecnologia e Inovação", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Redação e Leitura", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Eletiva", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Robótica", categoria: "PD", cargaHorariaSemanal: 2 },
          { nome: "Práticas Experimentais", categoria: "PD", cargaHorariaSemanal: 1 },
          { nome: "Esporte-música-arte", categoria: "PD", cargaHorariaSemanal: 2 },
        ],
      },
    ],
  },
  {
    id: "pei_medio_7h_matcnt",
    label: "PEI - Ensino Médio 7H - Itinerário Matemática e Ciências da Natureza",
    nivel: "medio",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Inglês", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Oe Matemática", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Oe Língua Portuguesa", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Eletiva", categoria: "IF", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 1 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Oe Matemática", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Oe Língua Portuguesa", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Eletiva", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Empreendedorismo", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Programação", categoria: "IF", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 1 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Oe Matemática", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Oe Língua Portuguesa", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Eletiva", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Práticas Experimentais", categoria: "IF", cargaHorariaSemanal: 3 },
          { nome: "Empreendedorismo", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Programação", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Biotecnologia", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Química Aplicada", categoria: "IF", cargaHorariaSemanal: 2 },
        ],
      },
    ],
  },
  {
    id: "pei_medio_7h_lggchs",
    label: "PEI - Ensino Médio 7H - Itinerário Linguagens e Ciências Humanas",
    nivel: "medio",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Inglês", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Oe Matemática", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Oe Língua Portuguesa", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Eletiva", categoria: "IF", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 1 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Oe Matemática", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Oe Língua Portuguesa", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Eletiva", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Liderança", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Oratória", categoria: "IF", cargaHorariaSemanal: 1 },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 1 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Oe Matemática", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Oe Língua Portuguesa", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Eletiva", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Práticas Experimentais", categoria: "IF", cargaHorariaSemanal: 3 },
          { nome: "Arte e Mídias Digitais", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Oratória", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Geopolítica", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Filosofia e Sociedade Moderna", categoria: "IF", cargaHorariaSemanal: 2 },
        ],
      },
    ],
  },
  {
    id: "pei_medio_9h_matcnt",
    label: "PEI - Ensino Médio 9H - Itinerário Matemática e Ciências da Natureza",
    nivel: "medio",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Inglês", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Oe Matemática", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Oe Língua Portuguesa", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Eletiva", categoria: "IF", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 1 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Oe Matemática", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Oe Língua Portuguesa", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Eletiva", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Empreendedorismo", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Programação", categoria: "IF", cargaHorariaSemanal: 2 },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 1 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Oe Matemática", categoria: "IF", cargaHorariaSemanal: 3 },
          { nome: "Oe Língua Portuguesa", categoria: "IF", cargaHorariaSemanal: 3 },
          { nome: "Eletiva", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Práticas Experimentais", categoria: "IF", cargaHorariaSemanal: 3 },
          { nome: "Empreendedorismo", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Programação", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Biotecnologia", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Química Aplicada", categoria: "IF", cargaHorariaSemanal: 2 },
        ],
      },
    ],
  },
  {
    id: "pei_medio_9h_lggchs",
    label: "PEI - Ensino Médio 9H - Itinerário Linguagens e Ciências Humanas",
    nivel: "medio",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Inglês", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Oe Matemática", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Oe Língua Portuguesa", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Eletiva", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Robótica", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Esporte-música-arte", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Práticas Experimentais", categoria: "IF", cargaHorariaSemanal: 1 },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 1 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Oe Matemática", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Oe Língua Portuguesa", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Eletiva", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Robótica", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Esporte-música-arte", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Práticas Experimentais", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Liderança", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Oratória", categoria: "IF", cargaHorariaSemanal: 1 },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Redação e Leitura", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 1 },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 4 },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2 },
          { nome: "Projeto de Vida", categoria: "IF", cargaHorariaSemanal: 1 },
          { nome: "Oe Matemática", categoria: "IF", cargaHorariaSemanal: 3 },
          { nome: "Oe Língua Portuguesa", categoria: "IF", cargaHorariaSemanal: 3 },
          { nome: "Eletiva", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Robótica", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Esporte-música-arte", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Práticas Experimentais", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Arte e Mídias Digitais", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Oratória", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Geopolítica", categoria: "IF", cargaHorariaSemanal: 2 },
          { nome: "Filosofia e Sociedade Moderna", categoria: "IF", cargaHorariaSemanal: 2 },
        ],
      },
    ],
  },
];