// Matrizes curriculares oficiais SEED-PR para Educação Profissional Técnica
// de Nível Médio, forma concomitante intercomplementar, ano de implantação 2026
// (Instrução Normativa Conjunta n.º 005/2026 - DEDUC/DPGE/SEED, versão finalizada
// de abril/2026). Fonte: documento oficial fornecido pela escola.
//
// IMPORTANTE: o documento original também traz uma série de códigos mais antiga
// (2318-2399), com totais crescentes por série — provavelmente a matriz de
// transição para alunos que já estavam cursando antes de 2026. Aqui usamos só a
// série 4800-4816, explicitamente marcada como "Ano de Implantação: 2026" — a
// que vale para novas matrículas. Se sua escola tiver turmas na matriz antiga,
// avise que extraímos aquela também.
//
// A Formação Geral Básica (FGB) é idêntica em todos os cursos (validado contra 3
// cursos de eixos diferentes). As disciplinas técnicas de cada curso (antes
// divididas em Aprofundamento / Itinerário Formativo / Itinerário Formativo
// Técnico Profissional na tabela original) foram agrupadas sob a categoria IFP —
// separá-las com precisão nas 3 subcategorias exigiria um parser mais frágil,
// então preferimos a simplificação segura em vez de arriscar erro de categoria.
//
// Língua Espanhola (Parte Diversificada, 4h/semana) é de matrícula facultativa
// para o aluno — incluída aqui como item não-obrigatório.

export interface ItemMatrizTecnica {
  nome: string;
  categoria: "FGB" | "IFP" | "PD";
  cargaHorariaSemanal: number;
  obrigatoria: boolean;
}

export interface MatrizTecnicaTemplate {
  codigo: string;
  curso: string;
  eixo: string;
  series: { serieAno: string; itens: ItemMatrizTecnica[] }[];
}

export const MATRIZES_TECNICAS_SEED_PR_2026: MatrizTecnicaTemplate[] = [
  {
    codigo: "4800",
    curso: "Técnico em Alimentos",
    eixo: "?",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Digital e Computação: Programação e IA", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução a Qualidade e Produtividade", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução a Indústria 4.0 e Introdução a", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução Ao Desenvolvimento de", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Princípios de Higiene e Segurança dos", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Fundamentos da Tecnologia de", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Fundamentos da Industrialização de", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Análise Físico-química de Alimentos e Formativo", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Criatividade e Ideação em Projetos de", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Análises Microbiológicas e", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Segurança e Controle de Qualidade dos Aprofundamento", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Modelagem de Projetos de Inovação", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Industrialização Óleos, Gorduras e Itinerário", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Industrialização de Leites e Derivados", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Industrialização Carnes, Ovos e Profissional", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Industrialização Bebidas", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Gestão de Produção II", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Prototipagem de Negócios Inovadores", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Implementação de Negócios Inovadores", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Industrialização Grãos, Cereais e", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Industrialização Balas, Chocolates e", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Industrialização Frutas, Hortaliças e", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Análises Sensoriais de Alimentos e", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Gestão de Produção I", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
    ],
  },
  {
    codigo: "4801",
    curso: "Técnico em Automação Industrial",
    eixo: "?",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Digital e Computação: Programação e IA", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução a Qualidade e Produtividade", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução a Indústria 4.0 e Introdução", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução Ao Desenvolvimento de", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Comunicação e Informática Aplicada", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Desenho Técnico Aplicado à Sistemas", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Fundamentos de Eletroeletrônica", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Lógica de Programação", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Criatividade e Ideação em Projetos de", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Acionamentos Eletroeletrônicos", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sistemas Eletrônicos e", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Gestão dos Processos de", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Sistemas Eletrohidráulicos e", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Instrumentação e Controle de", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Modelagem de Projetos de Inovação", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Comissionamento de Sistemas Itinerário", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Integração de Dispositivos Técnico", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Prototipagem de Negócios Inovadores", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sistemas Lógicos Programáveis", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Manutenção de Sistemas", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sistemas de Supervisão e Controle", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Projetos de Intertravamento de", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Projetos de Acionamentos", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Projetos de Controle e Sistemas", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Implementação de Negócios", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
    ],
  },
  {
    codigo: "4802",
    curso: "Técnico em Biotecnologia",
    eixo: "?",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Digital e Computação: Programação e IA", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução a Qualidade e Produtividade e Sustentabilidade", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução a Indústria 4.0 e Introdução a Tecnologia da", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução Ao Desenvolvimento de Projetos e", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Fundamentos de", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Fundamentos de Química", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Fundamentos de", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Prestação de Serviços", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Análises Físico-químicas", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Bioquímica", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Criatividade e Ideação em", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Microbiologia Aplicada", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia Molecular", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Modelagem de Projetos de", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Prototipagem de Negócios", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Implementação de", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Imunologia", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Gestão da Produção", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Processos Produtivos de Insumos e Produtos", categoria: "IFP", cargaHorariaSemanal: 4, obrigatoria: true },
          { nome: "Projeto de Pesquisa e", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
    ],
  },
  {
    codigo: "4803",
    curso: "Técnico em Desenvolvimento de Sistemas",
    eixo: "?",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Digital e Computação: Programação e IA", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Lógica de Programação II", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Introdução a Qualidade e Produtividade e Sustentabilidade", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução Ao Formativo Desenvolvimento de Projetos e", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Lógica de Programação I", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Programação de", categoria: "IFP", cargaHorariaSemanal: 4, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Banco de Dados II", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Desenvolvimento de", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Modelagem de Sistemas", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Banco de Dados I", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Desenvolvimento de", categoria: "IFP", cargaHorariaSemanal: 4, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução a Indústria 4.0 e Introdução a Tecnologia da", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Fundamentos de", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Internet das Coisas II", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Teste de Sistemas", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Implantação de Sistemas", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Manutenção de Sistemas", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Fundamentos de", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Internet das Coisas I", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
    ],
  },
  {
    codigo: "4804",
    curso: "Técnico em Edificações",
    eixo: "?",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Digital e Computação: Programação e IA", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução a Qualidade e Produtividade e Sustentabilidade Nos", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução a Indústria 4.0 e Introdução a Tecnologia da Informação e", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução Ao Desenvolvimento de", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução a Projetos de Edificações e Viabilidade Técnica e Legal", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução à Mecânica dos Solos", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Desenho Técnico Para Projetos de", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Métodos Modernos de Construção e Inovações Tecnológicas em Projetos de", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Gestão de Equipes em Canteiros de", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Projetos Arquitetônicos", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Processos de Construção de", categoria: "IFP", cargaHorariaSemanal: 4, obrigatoria: true },
          { nome: "Projetos de Instalações Elétricas e Itinerário", categoria: "IFP", cargaHorariaSemanal: 4, obrigatoria: true },
          { nome: "Gestão de Máquinas, Técnico Equipamentos e Instalações em Obras de", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Planejamento da Construção de", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Projetos Estruturais e Projetos", categoria: "IFP", cargaHorariaSemanal: 4, obrigatoria: true },
          { nome: "Gestão da Construção de Estruturas em Edificações e Gestão da", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Gestão da Manutenção de Edificações, Gestão da Execução de", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
    ],
  },
  {
    codigo: "4805",
    curso: "Técnico em Eletroeletrônica",
    eixo: "?",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Digital e Computação: Programação e IA", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução Ao Desenvolvimento de Projetos e Saúde e Segurança No", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Fundamentos da Eletroeletrônica", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Fundamentos da", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Eletrônica Analógica", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Eletrônica Digital", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Instalação de Sistemas Elétricos", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Instalação de Sistemas Elétricos", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Instalação de Sistemas Elétricos", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Instalação de Sistemas", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Gestão da Instalação de", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Manutenção de Sistemas", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Manutenção de Sistemas", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução a Indústria 4.0 e Introdução a Tecnologia da Informação e", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Gestão da Manutenção de", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução a Qualidade e Produtividade e Sustentabilidade Nos", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Manutenção de Sistemas", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Projetos de Instalações Elétricas", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Projetos de Acionamento e", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Projetos de Circuitos Eletrônicos", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
    ],
  },
  {
    codigo: "4806",
    curso: "Técnico em Eletromecânica",
    eixo: "?",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Digital e Computação: Programação e IA", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução a Qualidade e Produtividade e Sustentabilidade Nos", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução a Indústria 4.0 e Introdução a Tecnologia da Informação", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução Ao Desenvolvimento de Projetos e Saúde e Segurança No", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Fundamentos da Tecnologia", categoria: "IFP", cargaHorariaSemanal: 4, obrigatoria: true },
          { nome: "Introdução à Fabricação Itinerário", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Organização da Produção", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Montagem de Sistemas If", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Manutenção Mecânica de", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Planejamento e Controle da", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Manutenção Mecânica de", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Manutenção de Sistemas", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Fabricação Mecânica Aplicada", categoria: "IFP", cargaHorariaSemanal: 4, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Fundamentos da Eletricidade", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Montagem de Sistemas Elétricos", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Metodologia de Projetos", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Controlador Lógico Programável", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Projeto de Inovação em", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Manutenção de Sistemas", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Manutenção Elétrica de", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
    ],
  },
  {
    codigo: "4807",
    curso: "Técnico em Eletrônica",
    eixo: "?",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Digital e Computação: Programação e IA", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução Ao Desenvolvimento de Projetos e Saúde e Segurança No", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Fundamentos da Eletroeletrônica", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Fundamentos da Itinerário", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Dispositivos Eletrônicos", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Sistemas Eletrônicos Digitais", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução a Indústria 4.0 e Introdução a Tecnologia da Informação e", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução a Qualidade e Produtividade e Sustentabilidade Nos", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Lógica de Programação", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Redes de Comunicação e", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Montagem e Instalação de", categoria: "IFP", cargaHorariaSemanal: 4, obrigatoria: true },
          { nome: "Gestão da Montagem e", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Gestão da Manutenção de", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Programação de Dispositivos", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Projetos de Sistemas Eletrônicos", categoria: "IFP", cargaHorariaSemanal: 4, obrigatoria: true },
          { nome: "Programação de Dispositivos", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Desenvolvimento de Interfaces", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Manutenção de Sistemas", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
    ],
  },
  {
    codigo: "4808",
    curso: "Técnico em Informática",
    eixo: "?",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Digital e Computação: Programação e IA", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução a Qualidade e Produtividade e Sustentabilidade Nos", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução a Indústria 4.0 e Introdução a Tecnologia da Informação e", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução Ao Desenvolvimento de Projetos e Saúde e Segurança No", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Estruturas de Computadores", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Instalação e Manutenção de", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Infraestrutura de Redes de", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Instalação e Manutenção de", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Lógica de Programação II", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Elaboração de Dashboards II", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Boas Práticas em Gestão de Ti", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Gestão da Segurança de Ti", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Lógica de Programação I", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Elaboração de Dashboards I", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Desenvolvimento de Sistemas", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Desenvolvimento de Sistemas", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Manipulação de Bancos de", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Projetos de Ti", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
    ],
  },
  {
    codigo: "4809",
    curso: "Técnico em Logística",
    eixo: "?",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Digital e Computação: Programação e IA", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução a Qualidade e Produtividade e Sustentabilidade Nos", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução a Indústria 4.0 e Introdução a Tecnologia da", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução Ao Aprofundamento Desenvolvimento de Projetos e Saúde", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução Aos Processos", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Métodos Quantitativos", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Gestão da Produção", categoria: "IFP", cargaHorariaSemanal: 5, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Gestão de Transporte e", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Processos de Armazenagem", categoria: "IFP", cargaHorariaSemanal: 4, obrigatoria: true },
          { nome: "Projeto de Integração de Formativo", categoria: "IFP", cargaHorariaSemanal: 5, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Logística Integrada", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Gestão de Suprimentos", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Logística Sustentável", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Projeto Final de Conclusão de", categoria: "IFP", cargaHorariaSemanal: 4, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
    ],
  },
  {
    codigo: "4810",
    curso: "Técnico em Manutenção Automotiva",
    eixo: "?",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Digital e Computação: Programação e IA", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução a Qualidade e Produtividade e Sustentabilidade Nos", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução a Indústria 4.0 e Introdução a Tecnologia da", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução Ao Desenvolvimento de Projetos e Saúde", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução Às Tecnologias e Processos da Manutenção", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Sistemas de Freios,", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sistemas Eletroeletrônicos", categoria: "IFP", cargaHorariaSemanal: 4, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução à Eletromobilidade", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Prototipagem de Negócios Aprofundamento Inovadores e Modelagem de Projetos", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Motores de Combustão Interna", categoria: "IFP", cargaHorariaSemanal: 4, obrigatoria: true },
          { nome: "Gestão da Manutenção", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Fundamentos e Tecnologias", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Inspeção Veicular", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Vistoria de Sinistros e Cautelar", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Criatividade e Ideação em Projetos de Inovação e", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Sistemas de Transmissão de", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Diagnósticos Avançados em", categoria: "IFP", cargaHorariaSemanal: 6, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
    ],
  },
  {
    codigo: "4811",
    curso: "Técnico em Manutenção de Máquinas Industriais",
    eixo: "?",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Digital e Computação: Programação e IA", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução a Qualidade e Produtividade e Sustentabilidade Nos", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução a Indústria 4.0 e Introdução a Tecnologia da", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução Ao Desenvolvimento de Projetos e", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Processos Básicos de", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Fundamentos da Tecnologia If", categoria: "IFP", cargaHorariaSemanal: 5, obrigatoria: true },
          { nome: "Otimização de Processos Produtivos Dedicados à Manutenção", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Metodologia de Projetos", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Organização da Produção", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Fabricação Mecânica", categoria: "IFP", cargaHorariaSemanal: 4, obrigatoria: true },
          { nome: "Tecnologias de Recuperação", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Planejamento e Controle da", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Projeto de Inovação em", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução a Controlados", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Manutenção de Máquinas e", categoria: "IFP", cargaHorariaSemanal: 6, obrigatoria: true },
          { nome: "Manutenção de Sistemas", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
    ],
  },
  {
    codigo: "4812",
    curso: "Técnico em Mecânica",
    eixo: "?",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Digital e Computação: Programação e IA", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução a Qualidade e Produtividade e Sustentabilidade Nos", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução a Indústria 4.0 e Introdução a Tecnologia da Informação", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução Ao Desenvolvimento de Projetos e Saúde e Segurança No", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Fundamentos da Tecnologia", categoria: "IFP", cargaHorariaSemanal: 4, obrigatoria: true },
          { nome: "Processos Básicos de", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Planejamento e Controle da", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Otimização de Processos de", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Processos de Fabricação", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Manutenção Mecânica Aplicada", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Planejamento e Controle da", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Processos de Fabricação Itinerário", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Manutenção Mecânica Técnico", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Projeto de Inovação em", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Metodologia de Projetos II", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Projeto de Inovação em", categoria: "IFP", cargaHorariaSemanal: 4, obrigatoria: true },
          { nome: "Desenvolvimento de Sistemas", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Introdução a Controladores", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Metodologia de Projetos I", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
    ],
  },
  {
    codigo: "4813",
    curso: "Técnico em Mecatrônica",
    eixo: "?",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Digital e Computação: Programação e IA", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução a Qualidade e Produtividade e", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução a Indústria 4.0 e Introdução a", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução Ao Desenvolvimento de Projetos Aprofundamento", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Comunicação e Informática Aplicada", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Criatividade e Ideação em Projetos de", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Modelagem de Projetos de Inovação", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Desenho Técnico Aplicado à Sistemas", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Gestão dos Processos de Implementação", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Mecânica Aplicada a Sistemas", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Fundamentos de Eletroeletrônica", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Lógica de Programação", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sistemas Microcontrolados", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Sistemas Eletrônicos", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Processos de Fabricação Mecânica", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Acionamentos Eletroeletrônicos", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Integração de Sistemas Robóticos e Profissional", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sistemas Eletrohidráulicos e", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sistemas Lógicos Programáveis", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Sistemas de Supervisão e Controle", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Projetos de Sistemas Mecatrônicos", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Manutenção de Sistemas Mecatrônicos", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Projetos de Sistemas Embarcados", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Projetos de Componentes Mecânicos", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Projetos de Acionamentos", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Implementação de Negócios Inovadores", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Prototipagem de Negócios Inovadores", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
    ],
  },
  {
    codigo: "4814",
    curso: "Técnico em Química",
    eixo: "?",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Digital e Computação: Programação e IA", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução a Qualidade e Produtividade e", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução a Indústria 4.0 e Introdução a", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução Ao Desenvolvimento de", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Comunicação e Informática e Criatividade", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Gestão das Equipes de Trabalho", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Fundamentos de Matemática e Física", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Fundamentos das Técnicas Laboratoriais e Formativo", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Fundamentos de Química Orgânica e", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Operações Unitárias Laboratoriais", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Fundamentos de Bioquímica e", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Físico-química Aplicada", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Fundamentos de Processos Químicos Profissional Industriais e Controle dos Processos Industriais e", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Modelagem de Projetos de Inovação", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Tratamento de Águas e Efluentes e", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Implementação de Negócios Inovadores", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Análises Instrumentais", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Pesquisas e Aplicação de Produtos e", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Operação de Processos Industriais", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Desenvolvimento de Métodos Analíticos,", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Prototipagem de Negócios Inovadores", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
    ],
  },
  {
    codigo: "4815",
    curso: "Técnico em Vestuário",
    eixo: "?",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Digital e Computação: Programação e IA", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução a Qualidade e Produtividade", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução a Indústria 4.0 e Introdução", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução Ao Desenvolvimento de", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Fundamentos da Confecção do", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Processo de Modelagem Industrial", categoria: "IFP", cargaHorariaSemanal: 5, obrigatoria: true },
          { nome: "Processo de Corte Industrial", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Especificações Técnicas de Produtos e", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Processo de Costura Industrial", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Análise Técnica do Desenvolvimento de If", categoria: "IFP", cargaHorariaSemanal: 4, obrigatoria: true },
          { nome: "Criatividade e Ideação em Projetos de Itinerário Inovação e Modelagem de Projetos de", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Controle dos Processos do Vestuário", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Gestão de Equipes da Confecção do Profissional Vestuário e Planejamento da Produção do", categoria: "IFP", cargaHorariaSemanal: 5, obrigatoria: true },
          { nome: "Inspeção e Controle da Qualidade de", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Prototipagem de Negócios Inovadores", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
    ],
  },
  {
    codigo: "4816",
    curso: "Técnico em Eletrotécnica",
    eixo: "?",
    series: [
      {
        serieAno: "1ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Arte", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Digital e Computação: Programação e IA", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Introdução a Qualidade e Produtividade e Sustentabilidade Nos", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução a Indústria 4.0 e Introdução a Tecnologia da Informação e", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Introdução Ao Desenvolvimento de", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Desenho Técnico Aplicado a", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Fundamentos de Eletricidade", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Fundamentos de Sistemas", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Criatividade e Ideação em Projetos", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "2ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Educação Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Educação Financeira", categoria: "FGB", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Sociologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Filosofia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Projetos Elétricos Prediais", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Instalação e Manutenção Elétrica", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Integração de Sistemas de If", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Integração de Sistemas Elétricos", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Modelagem de Projetos de Formativo", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Manutenção Elétrica Industrial", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
      {
        serieAno: "3ª Série",
        itens: [
          { nome: "Língua Portuguesa", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Língua Inglesa", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Matemática", categoria: "FGB", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Química", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Física", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Biologia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Geografia", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "História", categoria: "FGB", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Eficiência Energética", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Projetos Elétricos Industriais", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Instalações e Acionamentos", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Manutenção e Operação de Sistemas Elétricos de Potência - Sep, Instalações de Sistemas Elétricos de", categoria: "IFP", cargaHorariaSemanal: 3, obrigatoria: true },
          { nome: "Implementação de Negócios Inovadores e Prototipagem de Negócios", categoria: "IFP", cargaHorariaSemanal: 2, obrigatoria: true },
          { nome: "Gestão Operacional Integrada", categoria: "IFP", cargaHorariaSemanal: 1, obrigatoria: true },
          { nome: "Língua Espanhola", categoria: "PD", cargaHorariaSemanal: 4, obrigatoria: false },
        ],
      },
    ],
  },
];