// Script de seed — dados REAIS e completos da escola (todas as turmas,
// professores, disciplinas e quantidade de aulas por turma), extraídos
// dos relatórios oficiais da secretaria (grade por turma e grade por
// professor, manhã/tarde/noite, cruzados e validados entre si).
//
// ESCOPO DESTA VERSÃO: professores, disciplinas, turmas, a carga
// horária (turma_disciplinas) de cada combinação turma+disciplina com
// o professor responsável, e as aulas de CO-DOCÊNCIA real (duas
// pessoas dando a mesma aula) — via `turma_disciplinas.professorApoioId`,
// confirmadas em 6 duplas: Pedro+Lisiane, Cecília+Ivanir, Ivanir+Silmara,
// Julio+Juliana, Julio+Matheus e Gilberto+Lisiane (27 combinações
// turma+disciplina no total).
//
// NÃO inclui ainda:
//   - Hora-Atividade (disponibilidade_professores) — depende do regime
//     de contrato (20h/40h) de cada professor, ainda pendente de
//     confirmação (ver Resolução SEED n.º 7.200/2025, Art. 11).
//   - Grade dia-a-dia (horarios) — depende do gerador de horário
//     (RF-SOLV) ser rodado depois deste seed.
//   - Cursos/Matrizes Curriculares formais — turmas ficam com
//     matrizCurricularId nulo por enquanto; carga horária de cada
//     disciplina vem de turma_disciplinas.cargaHorariaSemanalOverride.
//
// Como rodar (na raiz do monorepo):
//   pnpm --filter @workspace/scripts run seed
//
// É seguro rodar mais de uma vez: o script apaga professores, turmas e
// disciplinas da escola "escola_default" antes de inserir de novo (os
// registros dependentes — professor_disciplinas, turma_disciplinas,
// horarios, disponibilidade — saem em cascata via foreign key).

import { db, pool } from "@workspace/db";
import {
  planosTable,
  disciplinasTable,
  professoresTable,
  professorDisciplinasTable,
  turmasTable,
  turmaDisciplinasTable,
  salasTable,
} from "@workspace/db/schema";
import { eq } from "drizzle-orm";

const ESCOLA_ID = "escola_default";

const PALETA_CORES = [
  "#1565C0", "#0D47A1", "#42A5F5", "#607D8B", "#43A047",
  "#FB8C00", "#8E24AA", "#00897B", "#6D4C41", "#3949AB",
  "#D81B60", "#5D4037", "#00ACC1", "#7CB342", "#F4511E",
];

function emailFromNome(nome: string): string {
  const semAcento = nome
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z\s]/g, "")
    .trim()
    .replace(/\s+/g, ".");
  return `${semAcento}@escola.exemplo.br`;
}

// Disciplinas reais da grade da escola. `codigoSae: null` = ainda sem
// código SAE oficial confirmado. 17 disciplinas centrais reaproveitam o
// código já usado no catálogo anterior; mais 51 disciplinas técnicas
// (Administração, Desenvolvimento de Sistemas, Farmácia, Meio Ambiente,
// Formação de Docentes) tiveram o código SAE confirmado via Instrução
// Normativa Conjunta n.º 001/2026 - DEDUC/DPGE/SEED (Matrizes
// Curriculares EPT Integrada). As demais (recomposição de
// aprendizagem, itens numerados de Ensino Médio Regular/Fundamental
// como "Geografia 1"/"Física 2", Híbrida etc.) seguem sem código —
// não cobertas por esse documento (são de outra normativa) ou não
// encontradas em nenhuma matriz.

const DISCIPLINAS_REAIS: Array<{ label: string; nome: string; codigoSae: string | null }> = [
  { label: "ADM FINANC E ORÇAMENTÁRIA", nome: "Adm Financ e Orçamentária", codigoSae: null },
  { label: "ANÁLISE CONT E QUIM AMB", nome: "Análise Cont e Quim Amb", codigoSae: "867" },
  { label: "ANÁLISE CONT E QUIM AMB 1", nome: "Análise Cont e Quim Amb 1", codigoSae: "6620" },
  { label: "ANÁLISE E MET P SISTEMAS", nome: "Análise e Met p Sistemas", codigoSae: "5316" },
  { label: "ANÁLISE PROJ DE SISTEMAS", nome: "Análise Proj de Sistemas", codigoSae: null },
  { label: "ARTE", nome: "Arte", codigoSae: "4100" },
  { label: "ARTE 2", nome: "Arte 2", codigoSae: null },
  { label: "ARTE PARANAENSE", nome: "Arte Paranaense", codigoSae: null },
  { label: "BANCO DE DADOS", nome: "Banco de Dados", codigoSae: "6510" },
  { label: "BANCO DE DADOS 1", nome: "Banco de Dados 1", codigoSae: "5400" },
  { label: "BANCO DE DADOS 2", nome: "Banco de Dados 2", codigoSae: "5600" },
  { label: "BASES BIO APLIC A SAUDE", nome: "Bases Bio Aplic a Saude", codigoSae: "4288" },
  { label: "BIOLOGIA", nome: "Biologia", codigoSae: "2500" },
  { label: "BIOLOGIA 2", nome: "Biologia 2", codigoSae: null },
  { label: "BIOSSEGURANÇA E SEG TRAB", nome: "Biossegurança e Seg Trab", codigoSae: "4290" },
  { label: "CIÊNCIAS", nome: "Ciências (Fundamental)", codigoSae: "2400" },
  { label: "CIÊNCIAS DE DADOS", nome: "Ciências de Dados", codigoSae: "4763" },
  { label: "COMPUTAÇÃO GRÁFICA", nome: "Computação Gráfica", codigoSae: null },
  { label: "COMUNICAÇÃO E VENDAS", nome: "Comunicação e Vendas", codigoSae: "5020" },
  { label: "CONTROLADORIA E FINANÇAS", nome: "Controladoria e Finanças", codigoSae: null },
  { label: "DES HUM E SOCIOEMOCIONAL", nome: "Des Hum e Socioemocional", codigoSae: "5216" },
  { label: "DIS PROD FAR E CORRELATOS", nome: "Dis Prod Far e Correlatos", codigoSae: "4291" },
  { label: "ED INCLUSIVA DIVERSIDADE", nome: "Ed Inclusiva Diversidade", codigoSae: "5303" },
  { label: "EDUCAÇÃO AMBIENTAL", nome: "Educação Ambiental", codigoSae: "310" },
  { label: "EDUCAÇÃO AMBIENTAL 1", nome: "Educação Ambiental 1", codigoSae: "6622" },
  { label: "EDUCAÇÃO DIGITAL", nome: "Educação Digital", codigoSae: null },
  { label: "EDUCAÇÃO FINANCEIRA", nome: "Educação Financeira", codigoSae: "EDFIN" },
  { label: "EDUCAÇÃO FÍSICA", nome: "Educação Física", codigoSae: "3200" },
  { label: "EMPREENDEDORISMO", nome: "Empreendedorismo", codigoSae: null },
  { label: "ENS.RELIGIOSO", nome: "Ensino Religioso", codigoSae: "6400" },
  { label: "EST DE IMP RIS AMBIENTAIS", nome: "Est de Imp Ris Ambientais", codigoSae: "1519" },
  { label: "ESTRATÉGIA DE MARKETING", nome: "Estratégia de Marketing", codigoSae: "5019" },
  { label: "ESTRATÉGIAS DE MARKETING", nome: "Estratégias de Marketing", codigoSae: "5019" },
  { label: "FARMACOLOGIA 1", nome: "Farmacologia 1", codigoSae: "5513" },
  { label: "FARMACOLOGIA 2", nome: "Farmacologia 2", codigoSae: "5514" },
  { label: "FARMÁCIA HOSPITALAR", nome: "Farmácia Hospitalar", codigoSae: "5319" },
  { label: "FIL.TEXTOS FILOSÓFICOS", nome: "Fil.textos Filosóficos", codigoSae: null },
  { label: "FILOSOFIA", nome: "Filosofia", codigoSae: "3100" },
  { label: "FINANÇAS EMPRESARIAIS", nome: "Finanças Empresariais", codigoSae: "5033" },
  { label: "FUND DA FISIOPATOLOGIA", nome: "Fund da Fisiopatologia", codigoSae: "5515" },
  { label: "FUNDAMENTOS DE FARMÁCIA", nome: "Fundamentos de Farmácia", codigoSae: "4295" },
  { label: "FÍSICA", nome: "Física", codigoSae: "2600" },
  { label: "FÍSICA 2", nome: "Física 2", codigoSae: null },
  { label: "FÍSICA 3", nome: "Física 3", codigoSae: null },
  { label: "GEOGRAFIA", nome: "Geografia", codigoSae: "2100" },
  { label: "GEOGRAFIA 1", nome: "Geografia 1", codigoSae: null },
  { label: "GEOGRAFIA DO PARANÁ", nome: "Geografia do Paraná", codigoSae: null },
  { label: "GESTÃO DE REC NATURAIS", nome: "Gestão de Rec Naturais", codigoSae: "868" },
  { label: "GESTÃO DE REC NATURAIS 1", nome: "Gestão de Rec Naturais 1", codigoSae: "6623" },
  { label: "GESTÃO DE RESÍDUOS", nome: "Gestão de Resíduos", codigoSae: "1928" },
  { label: "HIBRIDA", nome: "Hibrida", codigoSae: null },
  { label: "HISTÓRIA", nome: "História", codigoSae: "2200" },
  { label: "HISTÓRIA 1", nome: "História 1", codigoSae: null },
  { label: "HISTÓRIA DO PARANÁ", nome: "História do Paraná", codigoSae: null },
  { label: "IN TEC E EMPREENDEDORISMO", nome: "In Tec e Empreendedorismo", codigoSae: "5999" },
  { label: "INFORMÁTICA APLICADA", nome: "Informática Aplicada", codigoSae: "4420" },
  { label: "INFORMÁTICA EMPRESARIAL", nome: "Informática Empresarial", codigoSae: "5015" },
  { label: "INTRODUÇÃO À COMPUTAÇÃO", nome: "Introdução à Computação", codigoSae: "5314" },
  { label: "INTRODUÇÃO À PROGRAMAÇÃO", nome: "Introdução à Programação", codigoSae: "5315" },
  { label: "LEI REC. APREND. L. PORT", nome: "Leitura e Recomposição da Aprendizagem - Língua Portuguesa", codigoSae: null },
  { label: "LID E GESTÃO DE PESSOAS", nome: "Lid e Gestão de Pessoas", codigoSae: "5034" },
  { label: "LID ORG E GES DE PESSOAS", nome: "Lid Org e Ges de Pessoas", codigoSae: "5034" },
  { label: "LIT. E PROD. DE TEXTO", nome: "Lit. e Prod. de Texto", codigoSae: null },
  { label: "LÍNGUA INGLESA", nome: "Língua Estrangeira Moderna - Inglês", codigoSae: "1400" },
  { label: "LÍNGUA INGLESA 1", nome: "Língua Inglesa 1", codigoSae: null },
  { label: "LÍNGUA PORTUGUESA", nome: "Língua Portuguesa e Literatura", codigoSae: "1100" },
  { label: "LÓGICA COMPUTACIONAL", nome: "Lógica Computacional", codigoSae: "1348" },
  { label: "MAT BAS P ANOS INICIAIS", nome: "Mat Bas p Anos Iniciais", codigoSae: "6508" },
  { label: "MATEMÁTICA", nome: "Matemática", codigoSae: "2700" },
  { label: "MATEMÁTICA 2", nome: "Matemática 2", codigoSae: null },
  { label: "MET CIENT E COMUNICAÇÃO", nome: "Met Cient e Comunicação", codigoSae: "871" },
  { label: "NEGOCIAÇÃO E VENDAS", nome: "Negociação e Vendas", codigoSae: null },
  { label: "NOÇÕES DE DIREITO", nome: "Noções de Direito", codigoSae: null },
  { label: "ORG DO TRAB PEDAGÓGICO", nome: "Org do Trab Pedagógico", codigoSae: "1803" },
  { label: "PRINC. DE ADMINISTRAÇÃO", nome: "Princ. de Administração", codigoSae: "4129" },
  { label: "PRINCÍPIOS ECONÔMICOS", nome: "Princípios Econômicos", codigoSae: "5031" },
  { label: "PROG NO DES DE SISTEMAS", nome: "Prog no Des de Sistemas", codigoSae: null },
  { label: "PROGRAMAÇÃO BACK END", nome: "Programação Back End", codigoSae: "5900" },
  { label: "PROGRAMAÇÃO BACK END 1", nome: "Programação Back End 1", codigoSae: "5700" },
  { label: "PROGRAMAÇÃO FRONT END", nome: "Programação Front End", codigoSae: "4761" },
  { label: "PROGRAMAÇÃO MOBILE", nome: "Programação Mobile", codigoSae: "4491" },
  { label: "PROJETO DE VIDA", nome: "Projeto de Vida", codigoSae: "PV01" },
  { label: "QUÍMICA", nome: "Química", codigoSae: "2300" },
  { label: "QUÍMICA 1", nome: "Química 1", codigoSae: null },
  { label: "REC. APREND. L. PORT", nome: "Recomposição da Aprendizagem - Língua Portuguesa", codigoSae: null },
  { label: "REC. APREND. MATEMÁTICA", nome: "Recomposição da Aprendizagem - Matemática", codigoSae: null },
  { label: "RECURSOS HUMANOS", nome: "Recursos Humanos", codigoSae: "4450" },
  { label: "REDAÇÃO E LEITURA", nome: "Redação e Leitura", codigoSae: "RED01" },
  { label: "REDAÇÃO TÉCNICA", nome: "Redação Técnica", codigoSae: "126" },
  { label: "SAÚDE PÚBLICA", nome: "Saúde Pública", codigoSae: "3228" },
  { label: "SIST DE GESTÃO AMBIENTAL", nome: "Sist de Gestão Ambiental", codigoSae: "6713" },
  { label: "SOC.GOV.CIDAD E SOCIEDADE", nome: "Soc.gov.cidad e Sociedade", codigoSae: null },
  { label: "SOCIOLOGIA", nome: "Sociologia", codigoSae: "3300" },
  { label: "SOCIOLOGIA 1", nome: "Sociologia 1", codigoSae: null },
  { label: "TECNO. E FER. DE GESTÃO", nome: "Tecno. e Fer. de Gestão", codigoSae: null },
  { label: "TOXICOLOGIA", nome: "Toxicologia", codigoSae: "3511" },
  { label: "TRAB PED NA ED INFANTIL", nome: "Trab Ped na Ed Infantil", codigoSae: "1726" },
  { label: "TÉCNICAS INTEGRADAS", nome: "Técnicas Integradas", codigoSae: "6509" },
];

// Professores confirmados nos relatórios reais (nome em Proper Case;
// e-mail gerado automaticamente — ajustar depois se a escola tiver
// e-mails institucionais reais). cargaHorariaTotal fica no padrão da
// coluna (20h) até o regime de contrato de cada um ser confirmado.

const PROFESSORES_REAIS: string[] = [
  "Aline",
  "Anderson",
  "Andre",
  "Andreia",
  "Antonio Silva",
  "Arnaldo",
  "Carlos",
  "Cecilia",
  "Cesar",
  "Chrystian",
  "Cleide",
  "Crislaine",
  "Cristiane",
  "Daiane",
  "Debora",
  "Dorival",
  "Ednilson",
  "Eduarda",
  "Eduardo",
  "Eleciana",
  "Eliana",
  "Eliane",
  "Eliane Rocha",
  "Elisabete",
  "Elisangela",
  "Emanuele",
  "Felipe",
  "Fernanda",
  "Franciele de Assis",
  "Francielle",
  "Gabriela",
  "Geovani",
  "Geverson",
  "Gilberto",
  "Gleiciane",
  "Gustavo",
  "Heberton",
  "Hemelly",
  "Herica",
  "Ione",
  "Ivanir",
  "Ivete",
  "Jackson",
  "Janice",
  "Jordana",
  "João Lucas",
  "Juliana",
  "Julio",
  "Kethelin",
  "Lisiane",
  "Lorena",
  "Luciane",
  "Luis Fernando",
  "Marcio",
  "Mario",
  "Marise",
  "Maristela",
  "Marlete",
  "Marta",
  "Matheus",
  "Melina",
  "Mirian",
  "Nelson",
  "Patricia",
  "Paulo",
  "Pedro",
  "Priscila",
  "Rafael",
  "Ricardo",
  "Roberval",
  "Robson",
  "Rodrigo",
  "Salete",
  "Sarah",
  "Silmara",
  "Simone",
  "Soneide",
  "Sypriano",
  "Tiago",
  "Viviane",
  "Wellington",
  "Werediana",
  "Wildemberg",
  "Willian",
];

// Turmas reais (nome exatamente como veio da secretaria).

const TURMAS_REAIS: Array<{ nome: string; serie: string; turno: string; nivelEnsino: "fundamental" | "medio_tecnico" }> = [
  { nome: "1MA EM", serie: "1ª Série EM", turno: "matutino", nivelEnsino: "medio_tecnico" },
  { nome: "1MB DES", serie: "1ª Série DES", turno: "matutino", nivelEnsino: "medio_tecnico" },
  { nome: "1MC FAR", serie: "1ª Série FAR", turno: "matutino", nivelEnsino: "medio_tecnico" },
  { nome: "1MD MA", serie: "1ª Série MA", turno: "matutino", nivelEnsino: "medio_tecnico" },
  { nome: "1ME DOC", serie: "1ª Série DOC", turno: "matutino", nivelEnsino: "medio_tecnico" },
  { nome: "1NB", serie: "1ª Série", turno: "noturno", nivelEnsino: "medio_tecnico" },
  { nome: "1NF ADM", serie: "1ª Série ADM", turno: "noturno", nivelEnsino: "medio_tecnico" },
  { nome: "2MA ADM", serie: "2ª Série ADM", turno: "matutino", nivelEnsino: "medio_tecnico" },
  { nome: "2MA EM", serie: "2ª Série EM", turno: "matutino", nivelEnsino: "medio_tecnico" },
  { nome: "2MB DES", serie: "2ª Série DES", turno: "matutino", nivelEnsino: "medio_tecnico" },
  { nome: "2MC FAR", serie: "2ª Série FAR", turno: "matutino", nivelEnsino: "medio_tecnico" },
  { nome: "2MD MA", serie: "2ª Série MA", turno: "matutino", nivelEnsino: "medio_tecnico" },
  { nome: "2NB", serie: "2ª Série", turno: "noturno", nivelEnsino: "medio_tecnico" },
  { nome: "2NC", serie: "2ª Série", turno: "noturno", nivelEnsino: "medio_tecnico" },
  { nome: "3MA ADM", serie: "3ª Série ADM", turno: "matutino", nivelEnsino: "medio_tecnico" },
  { nome: "3MA EM", serie: "3ª Série EM", turno: "matutino", nivelEnsino: "medio_tecnico" },
  { nome: "3MB DES", serie: "3ª Série DES", turno: "matutino", nivelEnsino: "medio_tecnico" },
  { nome: "3NB", serie: "3ª Série", turno: "noturno", nivelEnsino: "medio_tecnico" },
  { nome: "3NC", serie: "3ª Série", turno: "noturno", nivelEnsino: "medio_tecnico" },
  { nome: "6TA", serie: "6º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "6TB", serie: "6º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "6TC", serie: "6º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "6TD", serie: "6º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "6TE", serie: "6º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "6TF", serie: "6º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "6TG", serie: "6º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "6TH", serie: "6º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "6TI", serie: "6º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "7TA", serie: "7º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "7TB", serie: "7º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "7TC", serie: "7º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "7TD", serie: "7º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "7TE", serie: "7º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "7TF", serie: "7º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "7TG", serie: "7º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "7TH", serie: "7º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "8MA", serie: "8º Ano", turno: "matutino", nivelEnsino: "fundamental" },
  { nome: "8MB", serie: "8º Ano", turno: "matutino", nivelEnsino: "fundamental" },
  { nome: "8MC", serie: "8º Ano", turno: "matutino", nivelEnsino: "fundamental" },
  { nome: "8MD", serie: "8º Ano", turno: "matutino", nivelEnsino: "fundamental" },
  { nome: "8ME", serie: "8º Ano", turno: "matutino", nivelEnsino: "fundamental" },
  { nome: "8TF", serie: "8º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "8TG", serie: "8º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "8TH", serie: "8º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "9MA", serie: "9º Ano", turno: "matutino", nivelEnsino: "fundamental" },
  { nome: "9MB", serie: "9º Ano", turno: "matutino", nivelEnsino: "fundamental" },
  { nome: "9MC", serie: "9º Ano", turno: "matutino", nivelEnsino: "fundamental" },
  { nome: "9MD", serie: "9º Ano", turno: "matutino", nivelEnsino: "fundamental" },
  { nome: "9ME", serie: "9º Ano", turno: "matutino", nivelEnsino: "fundamental" },
  { nome: "9MF", serie: "9º Ano", turno: "matutino", nivelEnsino: "fundamental" },
  { nome: "9TG", serie: "9º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "9TH", serie: "9º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
  { nome: "9TI", serie: "9º Ano", turno: "vespertino", nivelEnsino: "fundamental" },
];

// Grade real: para cada (turma, disciplina), o professor responsável
// (professor titular) e, quando há CO-DOCÊNCIA real confirmada pela
// escola (duas pessoas dando a mesma aula, no mesmo dia/horário),
// também o professor de apoio. `professor: null` = HIBRIDA (aula
// híbrida sem professor regular associado no relatório de origem).

const GRADE_REAL: Array<{ turma: string; discLabel: string; professor: string | null; professorApoio: string | null; aulas: number }> = [
  { turma: "8MA", discLabel: "ARTE", professor: "Priscila", professorApoio: null, aulas: 2 },
  { turma: "8MA", discLabel: "EDUCAÇÃO FÍSICA", professor: "Heberton", professorApoio: null, aulas: 2 },
  { turma: "8MA", discLabel: "LÍNGUA INGLESA", professor: "Marise", professorApoio: null, aulas: 2 },
  { turma: "8MA", discLabel: "LÍNGUA PORTUGUESA", professor: "Gabriela", professorApoio: null, aulas: 3 },
  { turma: "8MA", discLabel: "GEOGRAFIA", professor: "Emanuele", professorApoio: null, aulas: 2 },
  { turma: "8MA", discLabel: "HISTÓRIA", professor: "Ednilson", professorApoio: null, aulas: 3 },
  { turma: "8MA", discLabel: "MATEMÁTICA", professor: "Andre", professorApoio: null, aulas: 4 },
  { turma: "8MA", discLabel: "EDUCAÇÃO DIGITAL", professor: "Silmara", professorApoio: null, aulas: 2 },
  { turma: "8MA", discLabel: "CIÊNCIAS", professor: "Rodrigo", professorApoio: null, aulas: 3 },
  { turma: "8MA", discLabel: "REDAÇÃO E LEITURA", professor: "Chrystian", professorApoio: null, aulas: 2 },
  { turma: "8MB", discLabel: "ARTE", professor: "Priscila", professorApoio: null, aulas: 2 },
  { turma: "8MB", discLabel: "EDUCAÇÃO FÍSICA", professor: "Heberton", professorApoio: null, aulas: 2 },
  { turma: "8MB", discLabel: "LÍNGUA INGLESA", professor: "Marise", professorApoio: null, aulas: 2 },
  { turma: "8MB", discLabel: "LÍNGUA PORTUGUESA", professor: "Gabriela", professorApoio: null, aulas: 3 },
  { turma: "8MB", discLabel: "GEOGRAFIA", professor: "Emanuele", professorApoio: null, aulas: 2 },
  { turma: "8MB", discLabel: "HISTÓRIA", professor: "Mario", professorApoio: null, aulas: 3 },
  { turma: "8MB", discLabel: "MATEMÁTICA", professor: "Andre", professorApoio: null, aulas: 4 },
  { turma: "8MB", discLabel: "EDUCAÇÃO DIGITAL", professor: "Silmara", professorApoio: null, aulas: 2 },
  { turma: "8MB", discLabel: "CIÊNCIAS", professor: "Rodrigo", professorApoio: null, aulas: 3 },
  { turma: "8MB", discLabel: "REDAÇÃO E LEITURA", professor: "Chrystian", professorApoio: null, aulas: 2 },
  { turma: "8MC", discLabel: "ARTE", professor: "Priscila", professorApoio: null, aulas: 2 },
  { turma: "8MC", discLabel: "EDUCAÇÃO FÍSICA", professor: "Heberton", professorApoio: null, aulas: 2 },
  { turma: "8MC", discLabel: "LÍNGUA INGLESA", professor: "Marise", professorApoio: null, aulas: 2 },
  { turma: "8MC", discLabel: "LÍNGUA PORTUGUESA", professor: "Gabriela", professorApoio: null, aulas: 3 },
  { turma: "8MC", discLabel: "GEOGRAFIA", professor: "Emanuele", professorApoio: null, aulas: 2 },
  { turma: "8MC", discLabel: "HISTÓRIA", professor: "Mario", professorApoio: null, aulas: 3 },
  { turma: "8MC", discLabel: "MATEMÁTICA", professor: "Andre", professorApoio: null, aulas: 4 },
  { turma: "8MC", discLabel: "EDUCAÇÃO DIGITAL", professor: "Silmara", professorApoio: null, aulas: 2 },
  { turma: "8MC", discLabel: "CIÊNCIAS", professor: "Rodrigo", professorApoio: null, aulas: 3 },
  { turma: "8MC", discLabel: "REDAÇÃO E LEITURA", professor: "Chrystian", professorApoio: null, aulas: 2 },
  { turma: "8MD", discLabel: "ARTE", professor: "Priscila", professorApoio: null, aulas: 2 },
  { turma: "8MD", discLabel: "EDUCAÇÃO FÍSICA", professor: "Heberton", professorApoio: null, aulas: 2 },
  { turma: "8MD", discLabel: "LÍNGUA INGLESA", professor: "Marise", professorApoio: null, aulas: 2 },
  { turma: "8MD", discLabel: "LÍNGUA PORTUGUESA", professor: "Gabriela", professorApoio: null, aulas: 3 },
  { turma: "8MD", discLabel: "GEOGRAFIA", professor: "Emanuele", professorApoio: null, aulas: 2 },
  { turma: "8MD", discLabel: "HISTÓRIA", professor: "Ednilson", professorApoio: null, aulas: 3 },
  { turma: "8MD", discLabel: "MATEMÁTICA", professor: "Andre", professorApoio: null, aulas: 4 },
  { turma: "8MD", discLabel: "EDUCAÇÃO DIGITAL", professor: "Silmara", professorApoio: null, aulas: 2 },
  { turma: "8MD", discLabel: "CIÊNCIAS", professor: "Rodrigo", professorApoio: null, aulas: 3 },
  { turma: "8MD", discLabel: "REDAÇÃO E LEITURA", professor: "Chrystian", professorApoio: null, aulas: 2 },
  { turma: "8ME", discLabel: "ARTE", professor: "Priscila", professorApoio: null, aulas: 2 },
  { turma: "8ME", discLabel: "EDUCAÇÃO FÍSICA", professor: "Heberton", professorApoio: null, aulas: 2 },
  { turma: "8ME", discLabel: "LÍNGUA INGLESA", professor: "Marise", professorApoio: null, aulas: 2 },
  { turma: "8ME", discLabel: "LÍNGUA PORTUGUESA", professor: "Gabriela", professorApoio: null, aulas: 3 },
  { turma: "8ME", discLabel: "GEOGRAFIA", professor: "Emanuele", professorApoio: null, aulas: 2 },
  { turma: "8ME", discLabel: "HISTÓRIA", professor: "Robson", professorApoio: null, aulas: 3 },
  { turma: "8ME", discLabel: "MATEMÁTICA", professor: "Geovani", professorApoio: null, aulas: 4 },
  { turma: "8ME", discLabel: "EDUCAÇÃO DIGITAL", professor: "Silmara", professorApoio: null, aulas: 2 },
  { turma: "8ME", discLabel: "CIÊNCIAS", professor: "Rodrigo", professorApoio: null, aulas: 3 },
  { turma: "8ME", discLabel: "REDAÇÃO E LEITURA", professor: "Chrystian", professorApoio: null, aulas: 2 },
  { turma: "9MA", discLabel: "ARTE", professor: "Lorena", professorApoio: null, aulas: 2 },
  { turma: "9MA", discLabel: "EDUCAÇÃO FÍSICA", professor: "Elisangela", professorApoio: null, aulas: 2 },
  { turma: "9MA", discLabel: "LÍNGUA INGLESA", professor: "Herica", professorApoio: null, aulas: 2 },
  { turma: "9MA", discLabel: "LÍNGUA PORTUGUESA", professor: "Fernanda", professorApoio: null, aulas: 3 },
  { turma: "9MA", discLabel: "GEOGRAFIA", professor: "Ricardo", professorApoio: null, aulas: 3 },
  { turma: "9MA", discLabel: "HISTÓRIA", professor: "Salete", professorApoio: null, aulas: 2 },
  { turma: "9MA", discLabel: "MATEMÁTICA", professor: "Eliana", professorApoio: null, aulas: 5 },
  { turma: "9MA", discLabel: "REC. APREND. MATEMÁTICA", professor: "Juliana", professorApoio: "Julio", aulas: 2 },
  { turma: "9MA", discLabel: "CIÊNCIAS", professor: "Cleide", professorApoio: null, aulas: 2 },
  { turma: "9MA", discLabel: "LEI REC. APREND. L. PORT", professor: "Ivanir", professorApoio: null, aulas: 2 },
  { turma: "9MB", discLabel: "ARTE", professor: "Lorena", professorApoio: null, aulas: 2 },
  { turma: "9MB", discLabel: "EDUCAÇÃO FÍSICA", professor: "Heberton", professorApoio: null, aulas: 2 },
  { turma: "9MB", discLabel: "LÍNGUA INGLESA", professor: "Herica", professorApoio: null, aulas: 2 },
  { turma: "9MB", discLabel: "LÍNGUA PORTUGUESA", professor: "Fernanda", professorApoio: null, aulas: 3 },
  { turma: "9MB", discLabel: "GEOGRAFIA", professor: "Ricardo", professorApoio: null, aulas: 3 },
  { turma: "9MB", discLabel: "HISTÓRIA", professor: "Salete", professorApoio: null, aulas: 2 },
  { turma: "9MB", discLabel: "MATEMÁTICA", professor: "Eliana", professorApoio: null, aulas: 5 },
  { turma: "9MB", discLabel: "REC. APREND. MATEMÁTICA", professor: "Juliana", professorApoio: "Julio", aulas: 2 },
  { turma: "9MB", discLabel: "CIÊNCIAS", professor: "Cleide", professorApoio: null, aulas: 2 },
  { turma: "9MB", discLabel: "LEI REC. APREND. L. PORT", professor: "Ivanir", professorApoio: null, aulas: 2 },
  { turma: "9MC", discLabel: "ARTE", professor: "Lorena", professorApoio: null, aulas: 2 },
  { turma: "9MC", discLabel: "EDUCAÇÃO FÍSICA", professor: "Heberton", professorApoio: null, aulas: 2 },
  { turma: "9MC", discLabel: "LÍNGUA INGLESA", professor: "Eduarda", professorApoio: null, aulas: 2 },
  { turma: "9MC", discLabel: "LÍNGUA PORTUGUESA", professor: "Fernanda", professorApoio: null, aulas: 3 },
  { turma: "9MC", discLabel: "GEOGRAFIA", professor: "Jackson", professorApoio: null, aulas: 3 },
  { turma: "9MC", discLabel: "HISTÓRIA", professor: "Salete", professorApoio: null, aulas: 2 },
  { turma: "9MC", discLabel: "MATEMÁTICA", professor: "Eliana", professorApoio: null, aulas: 5 },
  { turma: "9MC", discLabel: "REC. APREND. MATEMÁTICA", professor: "Juliana", professorApoio: "Julio", aulas: 2 },
  { turma: "9MC", discLabel: "CIÊNCIAS", professor: "Cleide", professorApoio: null, aulas: 2 },
  { turma: "9MC", discLabel: "LEI REC. APREND. L. PORT", professor: "Ivanir", professorApoio: null, aulas: 2 },
  { turma: "9MD", discLabel: "ARTE", professor: "Lorena", professorApoio: null, aulas: 2 },
  { turma: "9MD", discLabel: "EDUCAÇÃO FÍSICA", professor: "Elisangela", professorApoio: null, aulas: 2 },
  { turma: "9MD", discLabel: "LÍNGUA INGLESA", professor: "Eduarda", professorApoio: null, aulas: 2 },
  { turma: "9MD", discLabel: "LÍNGUA PORTUGUESA", professor: "Fernanda", professorApoio: null, aulas: 3 },
  { turma: "9MD", discLabel: "GEOGRAFIA", professor: "Ricardo", professorApoio: null, aulas: 3 },
  { turma: "9MD", discLabel: "HISTÓRIA", professor: "Mario", professorApoio: null, aulas: 2 },
  { turma: "9MD", discLabel: "MATEMÁTICA", professor: "Matheus", professorApoio: null, aulas: 5 },
  { turma: "9MD", discLabel: "REC. APREND. MATEMÁTICA", professor: "Juliana", professorApoio: "Julio", aulas: 2 },
  { turma: "9MD", discLabel: "CIÊNCIAS", professor: "Cleide", professorApoio: null, aulas: 2 },
  { turma: "9MD", discLabel: "LEI REC. APREND. L. PORT", professor: "Ivanir", professorApoio: null, aulas: 2 },
  { turma: "9ME", discLabel: "ARTE", professor: "Lorena", professorApoio: null, aulas: 2 },
  { turma: "9ME", discLabel: "EDUCAÇÃO FÍSICA", professor: "Heberton", professorApoio: null, aulas: 2 },
  { turma: "9ME", discLabel: "LÍNGUA INGLESA", professor: "Eliane Rocha", professorApoio: null, aulas: 2 },
  { turma: "9ME", discLabel: "LÍNGUA PORTUGUESA", professor: "Fernanda", professorApoio: null, aulas: 3 },
  { turma: "9ME", discLabel: "GEOGRAFIA", professor: "Ricardo", professorApoio: null, aulas: 3 },
  { turma: "9ME", discLabel: "HISTÓRIA", professor: "Salete", professorApoio: null, aulas: 2 },
  { turma: "9ME", discLabel: "MATEMÁTICA", professor: "Matheus", professorApoio: null, aulas: 5 },
  { turma: "9ME", discLabel: "REC. APREND. MATEMÁTICA", professor: "Matheus", professorApoio: "Julio", aulas: 2 },
  { turma: "9ME", discLabel: "CIÊNCIAS", professor: "Cleide", professorApoio: null, aulas: 2 },
  { turma: "9ME", discLabel: "LEI REC. APREND. L. PORT", professor: "Ivanir", professorApoio: null, aulas: 2 },
  { turma: "9MF", discLabel: "ARTE", professor: "Lorena", professorApoio: null, aulas: 2 },
  { turma: "9MF", discLabel: "EDUCAÇÃO FÍSICA", professor: "Heberton", professorApoio: null, aulas: 2 },
  { turma: "9MF", discLabel: "LÍNGUA INGLESA", professor: "Eliane Rocha", professorApoio: null, aulas: 2 },
  { turma: "9MF", discLabel: "LÍNGUA PORTUGUESA", professor: "Eduarda", professorApoio: null, aulas: 3 },
  { turma: "9MF", discLabel: "GEOGRAFIA", professor: "Jackson", professorApoio: null, aulas: 3 },
  { turma: "9MF", discLabel: "HISTÓRIA", professor: "Salete", professorApoio: null, aulas: 2 },
  { turma: "9MF", discLabel: "MATEMÁTICA", professor: "Geovani", professorApoio: null, aulas: 5 },
  { turma: "9MF", discLabel: "REC. APREND. MATEMÁTICA", professor: "Matheus", professorApoio: "Julio", aulas: 2 },
  { turma: "9MF", discLabel: "CIÊNCIAS", professor: "Cleide", professorApoio: null, aulas: 2 },
  { turma: "9MF", discLabel: "LEI REC. APREND. L. PORT", professor: "Ivanir", professorApoio: null, aulas: 2 },
  { turma: "1MA EM", discLabel: "ARTE", professor: "Jordana", professorApoio: null, aulas: 2 },
  { turma: "1MA EM", discLabel: "EDUCAÇÃO FÍSICA", professor: "Cristiane", professorApoio: null, aulas: 2 },
  { turma: "1MA EM", discLabel: "LÍNGUA INGLESA", professor: "Crislaine", professorApoio: null, aulas: 2 },
  { turma: "1MA EM", discLabel: "LÍNGUA PORTUGUESA", professor: "Rafael", professorApoio: null, aulas: 4 },
  { turma: "1MA EM", discLabel: "GEOGRAFIA", professor: "Dorival", professorApoio: null, aulas: 2 },
  { turma: "1MA EM", discLabel: "MATEMÁTICA", professor: "Maristela", professorApoio: null, aulas: 4 },
  { turma: "1MA EM", discLabel: "EDUCAÇÃO FINANCEIRA", professor: "Franciele de Assis", professorApoio: null, aulas: 2 },
  { turma: "1MA EM", discLabel: "EDUCAÇÃO DIGITAL", professor: "Pedro", professorApoio: null, aulas: 2 },
  { turma: "1MA EM", discLabel: "QUÍMICA", professor: "Luis Fernando", professorApoio: null, aulas: 2 },
  { turma: "1MA EM", discLabel: "BIOLOGIA", professor: "Ione", professorApoio: null, aulas: 2 },
  { turma: "1MA EM", discLabel: "HISTÓRIA DO PARANÁ", professor: "Salete", professorApoio: null, aulas: 2 },
  { turma: "1MA EM", discLabel: "GEOGRAFIA DO PARANÁ", professor: "Dorival", professorApoio: null, aulas: 2 },
  { turma: "1MA EM", discLabel: "ARTE PARANAENSE", professor: "Jordana", professorApoio: null, aulas: 2 },
  { turma: "2MA EM", discLabel: "ARTE", professor: "Roberval", professorApoio: null, aulas: 2 },
  { turma: "2MA EM", discLabel: "EDUCAÇÃO FÍSICA", professor: "Cristiane", professorApoio: null, aulas: 2 },
  { turma: "2MA EM", discLabel: "LÍNGUA INGLESA", professor: "Crislaine", professorApoio: null, aulas: 2 },
  { turma: "2MA EM", discLabel: "LÍNGUA PORTUGUESA", professor: "Soneide", professorApoio: null, aulas: 4 },
  { turma: "2MA EM", discLabel: "FILOSOFIA", professor: "Sypriano", professorApoio: null, aulas: 2 },
  { turma: "2MA EM", discLabel: "HISTÓRIA", professor: "Salete", professorApoio: null, aulas: 2 },
  { turma: "2MA EM", discLabel: "SOCIOLOGIA", professor: "Ednilson", professorApoio: null, aulas: 2 },
  { turma: "2MA EM", discLabel: "MATEMÁTICA", professor: "Geverson", professorApoio: null, aulas: 4 },
  { turma: "2MA EM", discLabel: "EDUCAÇÃO FINANCEIRA", professor: "Maristela", professorApoio: null, aulas: 2 },
  { turma: "2MA EM", discLabel: "FÍSICA", professor: "João Lucas", professorApoio: null, aulas: 2 },
  { turma: "2MA EM", discLabel: "LIT. E PROD. DE TEXTO", professor: "Soneide", professorApoio: null, aulas: 2 },
  { turma: "2MA EM", discLabel: "FIL.TEXTOS FILOSÓFICOS", professor: "Sypriano", professorApoio: null, aulas: 2 },
  { turma: "2MA EM", discLabel: "SOC.GOV.CIDAD E SOCIEDADE", professor: "Dorival", professorApoio: null, aulas: 2 },
  { turma: "3MA EM", discLabel: "EDUCAÇÃO FÍSICA", professor: "Cristiane", professorApoio: null, aulas: 2 },
  { turma: "3MA EM", discLabel: "LÍNGUA PORTUGUESA", professor: "Aline", professorApoio: null, aulas: 4 },
  { turma: "3MA EM", discLabel: "MATEMÁTICA", professor: "Kethelin", professorApoio: null, aulas: 4 },
  { turma: "3MA EM", discLabel: "EDUCAÇÃO FINANCEIRA", professor: "Hemelly", professorApoio: null, aulas: 2 },
  { turma: "3MA EM", discLabel: "FÍSICA", professor: "Arnaldo", professorApoio: null, aulas: 2 },
  { turma: "3MA EM", discLabel: "PROJETO DE VIDA", professor: "Cesar", professorApoio: null, aulas: 1 },
  { turma: "3MA EM", discLabel: "REC. APREND. L. PORT", professor: "Chrystian", professorApoio: null, aulas: 2 },
  { turma: "3MA EM", discLabel: "REC. APREND. MATEMÁTICA", professor: "Mirian", professorApoio: null, aulas: 2 },
  { turma: "3MA EM", discLabel: "GEOGRAFIA 1", professor: "Ricardo", professorApoio: null, aulas: 2 },
  { turma: "3MA EM", discLabel: "HISTÓRIA 1", professor: "Gleiciane", professorApoio: null, aulas: 2 },
  { turma: "3MA EM", discLabel: "LÍNGUA INGLESA 1", professor: "Herica", professorApoio: null, aulas: 3 },
  { turma: "3MA EM", discLabel: "SOCIOLOGIA 1", professor: "Gleiciane", professorApoio: null, aulas: 2 },
  { turma: "3MA EM", discLabel: "ARTE 2", professor: "Roberval", professorApoio: null, aulas: 2 },
  { turma: "2MA ADM", discLabel: "EDUCAÇÃO FÍSICA", professor: "Cristiane", professorApoio: null, aulas: 2 },
  { turma: "2MA ADM", discLabel: "LÍNGUA INGLESA", professor: "Crislaine", professorApoio: null, aulas: 2 },
  { turma: "2MA ADM", discLabel: "LÍNGUA PORTUGUESA", professor: "Silmara", professorApoio: null, aulas: 3 },
  { turma: "2MA ADM", discLabel: "FILOSOFIA", professor: "Sypriano", professorApoio: null, aulas: 2 },
  { turma: "2MA ADM", discLabel: "HISTÓRIA", professor: "Salete", professorApoio: null, aulas: 2 },
  { turma: "2MA ADM", discLabel: "SOCIOLOGIA", professor: "Ednilson", professorApoio: null, aulas: 2 },
  { turma: "2MA ADM", discLabel: "MATEMÁTICA", professor: "Anderson", professorApoio: null, aulas: 2 },
  { turma: "2MA ADM", discLabel: "EDUCAÇÃO FINANCEIRA", professor: "Hemelly", professorApoio: null, aulas: 1 },
  { turma: "2MA ADM", discLabel: "FÍSICA", professor: "João Lucas", professorApoio: null, aulas: 2 },
  { turma: "2MA ADM", discLabel: "INFORMÁTICA EMPRESARIAL", professor: "Kethelin", professorApoio: null, aulas: 1 },
  { turma: "2MA ADM", discLabel: "COMUNICAÇÃO E VENDAS", professor: "Franciele de Assis", professorApoio: null, aulas: 1 },
  { turma: "2MA ADM", discLabel: "FINANÇAS EMPRESARIAIS", professor: "Franciele de Assis", professorApoio: null, aulas: 2 },
  { turma: "2MA ADM", discLabel: "LID ORG E GES DE PESSOAS", professor: "Simone", professorApoio: null, aulas: 2 },
  { turma: "2MA ADM", discLabel: "RECURSOS HUMANOS", professor: "Simone", professorApoio: null, aulas: 2 },
  { turma: "2MA ADM", discLabel: "ESTRATÉGIA DE MARKETING", professor: "Franciele de Assis", professorApoio: null, aulas: 2 },
  { turma: "2MA ADM", discLabel: "TÉCNICAS INTEGRADAS", professor: "Cecilia", professorApoio: null, aulas: 1 },
  { turma: "2MA ADM", discLabel: "PRINCÍPIOS ECONÔMICOS", professor: "Kethelin", professorApoio: null, aulas: 1 },
  { turma: "3MA ADM", discLabel: "EDUCAÇÃO FÍSICA", professor: "Cristiane", professorApoio: null, aulas: 2 },
  { turma: "3MA ADM", discLabel: "LÍNGUA PORTUGUESA", professor: "Soneide", professorApoio: null, aulas: 4 },
  { turma: "3MA ADM", discLabel: "MATEMÁTICA", professor: "Geverson", professorApoio: null, aulas: 4 },
  { turma: "3MA ADM", discLabel: "EDUCAÇÃO FINANCEIRA", professor: "Hemelly", professorApoio: null, aulas: 1 },
  { turma: "3MA ADM", discLabel: "FÍSICA", professor: "João Lucas", professorApoio: null, aulas: 2 },
  { turma: "3MA ADM", discLabel: "PROJETO DE VIDA", professor: "Cristiane", professorApoio: null, aulas: 1 },
  { turma: "3MA ADM", discLabel: "RECURSOS HUMANOS", professor: "Elisabete", professorApoio: null, aulas: 2 },
  { turma: "3MA ADM", discLabel: "ADM FINANC E ORÇAMENTÁRIA", professor: "Simone", professorApoio: null, aulas: 2 },
  { turma: "3MA ADM", discLabel: "TECNO. E FER. DE GESTÃO", professor: "Franciele de Assis", professorApoio: null, aulas: 2 },
  { turma: "3MA ADM", discLabel: "LID E GESTÃO DE PESSOAS", professor: "Francielle", professorApoio: null, aulas: 4 },
  { turma: "3MA ADM", discLabel: "NEGOCIAÇÃO E VENDAS", professor: "Simone", professorApoio: null, aulas: 2 },
  { turma: "3MA ADM", discLabel: "NOÇÕES DE DIREITO", professor: "Gleiciane", professorApoio: null, aulas: 2 },
  { turma: "3MA ADM", discLabel: "CONTROLADORIA E FINANÇAS", professor: "Simone", professorApoio: null, aulas: 2 },
  { turma: "1MB DES", discLabel: "ARTE", professor: "Jordana", professorApoio: null, aulas: 2 },
  { turma: "1MB DES", discLabel: "EDUCAÇÃO FÍSICA", professor: "Cristiane", professorApoio: null, aulas: 2 },
  { turma: "1MB DES", discLabel: "LÍNGUA INGLESA", professor: "Crislaine", professorApoio: null, aulas: 2 },
  { turma: "1MB DES", discLabel: "LÍNGUA PORTUGUESA", professor: "Aline", professorApoio: null, aulas: 2 },
  { turma: "1MB DES", discLabel: "GEOGRAFIA", professor: "Dorival", professorApoio: null, aulas: 2 },
  { turma: "1MB DES", discLabel: "MATEMÁTICA", professor: "Maristela", professorApoio: null, aulas: 3 },
  { turma: "1MB DES", discLabel: "EDUCAÇÃO DIGITAL", professor: "Pedro", professorApoio: null, aulas: 1 },
  { turma: "1MB DES", discLabel: "QUÍMICA", professor: "Elisabete", professorApoio: null, aulas: 2 },
  { turma: "1MB DES", discLabel: "BIOLOGIA", professor: "Ione", professorApoio: null, aulas: 2 },
  { turma: "1MB DES", discLabel: "ANÁLISE E MET P SISTEMAS", professor: "Simone", professorApoio: null, aulas: 3 },
  { turma: "1MB DES", discLabel: "INTRODUÇÃO À COMPUTAÇÃO", professor: "Gustavo", professorApoio: null, aulas: 2 },
  { turma: "1MB DES", discLabel: "LÓGICA COMPUTACIONAL", professor: "Gustavo", professorApoio: null, aulas: 2 },
  { turma: "1MB DES", discLabel: "BANCO DE DADOS 1", professor: "Simone", professorApoio: null, aulas: 3 },
  { turma: "1MB DES", discLabel: "INTRODUÇÃO À PROGRAMAÇÃO", professor: "Gustavo", professorApoio: null, aulas: 2 },
  { turma: "2MB DES", discLabel: "EDUCAÇÃO FÍSICA", professor: "Cristiane", professorApoio: null, aulas: 2 },
  { turma: "2MB DES", discLabel: "LÍNGUA INGLESA", professor: "Crislaine", professorApoio: null, aulas: 2 },
  { turma: "2MB DES", discLabel: "LÍNGUA PORTUGUESA", professor: "Silmara", professorApoio: null, aulas: 3 },
  { turma: "2MB DES", discLabel: "FILOSOFIA", professor: "Sypriano", professorApoio: null, aulas: 2 },
  { turma: "2MB DES", discLabel: "HISTÓRIA", professor: "Salete", professorApoio: null, aulas: 2 },
  { turma: "2MB DES", discLabel: "SOCIOLOGIA", professor: "Gleiciane", professorApoio: null, aulas: 2 },
  { turma: "2MB DES", discLabel: "MATEMÁTICA", professor: "Anderson", professorApoio: null, aulas: 2 },
  { turma: "2MB DES", discLabel: "EDUCAÇÃO FINANCEIRA", professor: "Hemelly", professorApoio: null, aulas: 1 },
  { turma: "2MB DES", discLabel: "FÍSICA", professor: "João Lucas", professorApoio: null, aulas: 2 },
  { turma: "2MB DES", discLabel: "IN TEC E EMPREENDEDORISMO", professor: "Emanuele", professorApoio: null, aulas: 3 },
  { turma: "2MB DES", discLabel: "PROGRAMAÇÃO BACK END 1", professor: "Gustavo", professorApoio: null, aulas: 3 },
  { turma: "2MB DES", discLabel: "PROGRAMAÇÃO FRONT END", professor: "Gustavo", professorApoio: null, aulas: 3 },
  { turma: "2MB DES", discLabel: "BANCO DE DADOS 2", professor: "Gustavo", professorApoio: null, aulas: 3 },
  { turma: "3MB DES", discLabel: "EDUCAÇÃO FÍSICA", professor: "Elisangela", professorApoio: null, aulas: 1 },
  { turma: "3MB DES", discLabel: "LÍNGUA PORTUGUESA", professor: "Crislaine", professorApoio: null, aulas: 4 },
  { turma: "3MB DES", discLabel: "MATEMÁTICA", professor: "Kethelin", professorApoio: null, aulas: 4 },
  { turma: "3MB DES", discLabel: "EDUCAÇÃO FINANCEIRA", professor: "Eliane Rocha", professorApoio: null, aulas: 1 },
  { turma: "3MB DES", discLabel: "FÍSICA", professor: "João Lucas", professorApoio: null, aulas: 1 },
  { turma: "3MB DES", discLabel: "ANÁLISE PROJ DE SISTEMAS", professor: "Eduarda", professorApoio: null, aulas: 3 },
  { turma: "3MB DES", discLabel: "BANCO DE DADOS", professor: "Arnaldo", professorApoio: null, aulas: 2 },
  { turma: "3MB DES", discLabel: "PROGRAMAÇÃO BACK END", professor: "Gustavo", professorApoio: null, aulas: 4 },
  { turma: "3MB DES", discLabel: "PROGRAMAÇÃO MOBILE", professor: "Kethelin", professorApoio: null, aulas: 2 },
  { turma: "3MB DES", discLabel: "PROG NO DES DE SISTEMAS", professor: "Arnaldo", professorApoio: null, aulas: 4 },
  { turma: "3MB DES", discLabel: "CIÊNCIAS DE DADOS", professor: "Kethelin", professorApoio: null, aulas: 2 },
  { turma: "3MB DES", discLabel: "COMPUTAÇÃO GRÁFICA", professor: "Gleiciane", professorApoio: null, aulas: 2 },
  { turma: "1MC FAR", discLabel: "ARTE", professor: "Lorena", professorApoio: null, aulas: 2 },
  { turma: "1MC FAR", discLabel: "EDUCAÇÃO FÍSICA", professor: "Cristiane", professorApoio: null, aulas: 2 },
  { turma: "1MC FAR", discLabel: "LÍNGUA INGLESA", professor: "Eliane Rocha", professorApoio: null, aulas: 2 },
  { turma: "1MC FAR", discLabel: "LÍNGUA PORTUGUESA", professor: "Aline", professorApoio: null, aulas: 2 },
  { turma: "1MC FAR", discLabel: "GEOGRAFIA", professor: "Dorival", professorApoio: null, aulas: 2 },
  { turma: "1MC FAR", discLabel: "MATEMÁTICA", professor: "Maristela", professorApoio: null, aulas: 3 },
  { turma: "1MC FAR", discLabel: "EDUCAÇÃO DIGITAL", professor: "Pedro", professorApoio: null, aulas: 1 },
  { turma: "1MC FAR", discLabel: "QUÍMICA", professor: "Elisabete", professorApoio: null, aulas: 2 },
  { turma: "1MC FAR", discLabel: "BIOLOGIA", professor: "Ione", professorApoio: null, aulas: 2 },
  { turma: "1MC FAR", discLabel: "REDAÇÃO TÉCNICA", professor: "Viviane", professorApoio: null, aulas: 1 },
  { turma: "1MC FAR", discLabel: "EMPREENDEDORISMO", professor: "Robson", professorApoio: null, aulas: 2 },
  { turma: "1MC FAR", discLabel: "DIS PROD FAR E CORRELATOS", professor: "Cecilia", professorApoio: null, aulas: 2 },
  { turma: "1MC FAR", discLabel: "FARMÁCIA HOSPITALAR", professor: "Cecilia", professorApoio: null, aulas: 1 },
  { turma: "1MC FAR", discLabel: "FARMACOLOGIA 1", professor: "Cecilia", professorApoio: null, aulas: 3 },
  { turma: "1MC FAR", discLabel: "FUNDAMENTOS DE FARMÁCIA", professor: "Cecilia", professorApoio: null, aulas: 2 },
  { turma: "1MC FAR", discLabel: "SAÚDE PÚBLICA", professor: "Melina", professorApoio: null, aulas: 1 },
  { turma: "2MC FAR", discLabel: "EDUCAÇÃO FÍSICA", professor: "Cristiane", professorApoio: null, aulas: 2 },
  { turma: "2MC FAR", discLabel: "LÍNGUA INGLESA", professor: "Crislaine", professorApoio: null, aulas: 2 },
  { turma: "2MC FAR", discLabel: "LÍNGUA PORTUGUESA", professor: "Aline", professorApoio: null, aulas: 3 },
  { turma: "2MC FAR", discLabel: "FILOSOFIA", professor: "Sypriano", professorApoio: null, aulas: 2 },
  { turma: "2MC FAR", discLabel: "HISTÓRIA", professor: "Salete", professorApoio: null, aulas: 2 },
  { turma: "2MC FAR", discLabel: "SOCIOLOGIA", professor: "Gleiciane", professorApoio: null, aulas: 2 },
  { turma: "2MC FAR", discLabel: "MATEMÁTICA", professor: "Anderson", professorApoio: null, aulas: 2 },
  { turma: "2MC FAR", discLabel: "EDUCAÇÃO FINANCEIRA", professor: "Hemelly", professorApoio: null, aulas: 1 },
  { turma: "2MC FAR", discLabel: "FÍSICA", professor: "João Lucas", professorApoio: null, aulas: 2 },
  { turma: "2MC FAR", discLabel: "BASES BIO APLIC A SAUDE", professor: "Werediana", professorApoio: null, aulas: 2 },
  { turma: "2MC FAR", discLabel: "REDAÇÃO TÉCNICA", professor: "Viviane", professorApoio: null, aulas: 1 },
  { turma: "2MC FAR", discLabel: "BIOSSEGURANÇA E SEG TRAB", professor: "Cecilia", professorApoio: null, aulas: 1 },
  { turma: "2MC FAR", discLabel: "DIS PROD FAR E CORRELATOS", professor: "Cecilia", professorApoio: null, aulas: 2 },
  { turma: "2MC FAR", discLabel: "FARMACOLOGIA 2", professor: "Cecilia", professorApoio: null, aulas: 2 },
  { turma: "2MC FAR", discLabel: "FUND DA FISIOPATOLOGIA", professor: "Viviane", professorApoio: null, aulas: 2 },
  { turma: "2MC FAR", discLabel: "TOXICOLOGIA", professor: "Viviane", professorApoio: null, aulas: 2 },
  { turma: "1MD MA", discLabel: "ARTE", professor: "Jordana", professorApoio: null, aulas: 2 },
  { turma: "1MD MA", discLabel: "EDUCAÇÃO FÍSICA", professor: "Cristiane", professorApoio: null, aulas: 2 },
  { turma: "1MD MA", discLabel: "LÍNGUA INGLESA", professor: "Crislaine", professorApoio: null, aulas: 2 },
  { turma: "1MD MA", discLabel: "LÍNGUA PORTUGUESA", professor: "Aline", professorApoio: null, aulas: 2 },
  { turma: "1MD MA", discLabel: "GEOGRAFIA", professor: "Dorival", professorApoio: null, aulas: 2 },
  { turma: "1MD MA", discLabel: "MATEMÁTICA", professor: "Maristela", professorApoio: null, aulas: 3 },
  { turma: "1MD MA", discLabel: "EDUCAÇÃO DIGITAL", professor: "Pedro", professorApoio: null, aulas: 1 },
  { turma: "1MD MA", discLabel: "QUÍMICA", professor: "Luis Fernando", professorApoio: null, aulas: 2 },
  { turma: "1MD MA", discLabel: "BIOLOGIA", professor: "Ione", professorApoio: null, aulas: 2 },
  { turma: "1MD MA", discLabel: "ANÁLISE CONT E QUIM AMB", professor: "Elisabete", professorApoio: null, aulas: 2 },
  { turma: "1MD MA", discLabel: "GESTÃO DE REC NATURAIS", professor: "Elisabete", professorApoio: null, aulas: 1 },
  { turma: "1MD MA", discLabel: "EDUCAÇÃO AMBIENTAL", professor: "Jackson", professorApoio: null, aulas: 2 },
  { turma: "1MD MA", discLabel: "GESTÃO DE RESÍDUOS", professor: "Ione", professorApoio: null, aulas: 2 },
  { turma: "1MD MA", discLabel: "INFORMÁTICA APLICADA", professor: "Emanuele", professorApoio: null, aulas: 2 },
  { turma: "1MD MA", discLabel: "SIST DE GESTÃO AMBIENTAL", professor: "Emanuele", professorApoio: null, aulas: 3 },
  { turma: "2MD MA", discLabel: "EDUCAÇÃO FÍSICA", professor: "Cristiane", professorApoio: null, aulas: 2 },
  { turma: "2MD MA", discLabel: "LÍNGUA INGLESA", professor: "Crislaine", professorApoio: null, aulas: 2 },
  { turma: "2MD MA", discLabel: "LÍNGUA PORTUGUESA", professor: "Aline", professorApoio: null, aulas: 3 },
  { turma: "2MD MA", discLabel: "FILOSOFIA", professor: "Cesar", professorApoio: null, aulas: 2 },
  { turma: "2MD MA", discLabel: "HISTÓRIA", professor: "Salete", professorApoio: null, aulas: 2 },
  { turma: "2MD MA", discLabel: "SOCIOLOGIA", professor: "Gleiciane", professorApoio: null, aulas: 2 },
  { turma: "2MD MA", discLabel: "MATEMÁTICA", professor: "Anderson", professorApoio: null, aulas: 2 },
  { turma: "2MD MA", discLabel: "EDUCAÇÃO FINANCEIRA", professor: "Hemelly", professorApoio: null, aulas: 1 },
  { turma: "2MD MA", discLabel: "FÍSICA", professor: "João Lucas", professorApoio: null, aulas: 2 },
  { turma: "2MD MA", discLabel: "EDUCAÇÃO AMBIENTAL 1", professor: "Elisabete", professorApoio: null, aulas: 1 },
  { turma: "2MD MA", discLabel: "EST DE IMP RIS AMBIENTAIS", professor: "Dorival", professorApoio: null, aulas: 2 },
  { turma: "2MD MA", discLabel: "ANÁLISE CONT E QUIM AMB 1", professor: "Viviane", professorApoio: null, aulas: 2 },
  { turma: "2MD MA", discLabel: "GESTÃO DE REC NATURAIS 1", professor: "Dorival", professorApoio: null, aulas: 2 },
  { turma: "2MD MA", discLabel: "GESTÃO DE RESÍDUOS", professor: "Emanuele", professorApoio: null, aulas: 2 },
  { turma: "2MD MA", discLabel: "MET CIENT E COMUNICAÇÃO", professor: "Viviane", professorApoio: null, aulas: 1 },
  { turma: "2MD MA", discLabel: "SIST DE GESTÃO AMBIENTAL", professor: "Elisabete", professorApoio: null, aulas: 2 },
  { turma: "1ME DOC", discLabel: "ARTE", professor: "Lorena", professorApoio: null, aulas: 2 },
  { turma: "1ME DOC", discLabel: "EDUCAÇÃO FÍSICA", professor: "Elisangela", professorApoio: null, aulas: 2 },
  { turma: "1ME DOC", discLabel: "LÍNGUA INGLESA", professor: "Eliane Rocha", professorApoio: null, aulas: 2 },
  { turma: "1ME DOC", discLabel: "LÍNGUA PORTUGUESA", professor: "Crislaine", professorApoio: null, aulas: 2 },
  { turma: "1ME DOC", discLabel: "GEOGRAFIA", professor: "Dorival", professorApoio: null, aulas: 2 },
  { turma: "1ME DOC", discLabel: "MATEMÁTICA", professor: "Anderson", professorApoio: null, aulas: 3 },
  { turma: "1ME DOC", discLabel: "EDUCAÇÃO DIGITAL", professor: "Pedro", professorApoio: null, aulas: 1 },
  { turma: "1ME DOC", discLabel: "QUÍMICA", professor: "Elisabete", professorApoio: null, aulas: 2 },
  { turma: "1ME DOC", discLabel: "BIOLOGIA", professor: "Ione", professorApoio: null, aulas: 2 },
  { turma: "1ME DOC", discLabel: "MAT BAS P ANOS INICIAIS", professor: "Eduarda", professorApoio: null, aulas: 3 },
  { turma: "1ME DOC", discLabel: "ORG DO TRAB PEDAGÓGICO", professor: "Julio", professorApoio: null, aulas: 2 },
  { turma: "1ME DOC", discLabel: "DES HUM E SOCIOEMOCIONAL", professor: "Eduarda", professorApoio: null, aulas: 2 },
  { turma: "1ME DOC", discLabel: "ED INCLUSIVA DIVERSIDADE", professor: "Cecilia", professorApoio: null, aulas: 3 },
  { turma: "1ME DOC", discLabel: "TRAB PED NA ED INFANTIL", professor: "Julio", professorApoio: null, aulas: 2 },
  { turma: "6TA", discLabel: "LÍNGUA PORTUGUESA", professor: "Rafael", professorApoio: null, aulas: 4 },
  { turma: "6TA", discLabel: "MATEMÁTICA", professor: "Robson", professorApoio: null, aulas: 4 },
  { turma: "6TA", discLabel: "HISTÓRIA", professor: "Daiane", professorApoio: null, aulas: 2 },
  { turma: "6TA", discLabel: "GEOGRAFIA", professor: "Ricardo", professorApoio: null, aulas: 2 },
  { turma: "6TA", discLabel: "ARTE", professor: "Priscila", professorApoio: null, aulas: 2 },
  { turma: "6TA", discLabel: "EDUCAÇÃO FÍSICA", professor: "Elisangela", professorApoio: null, aulas: 2 },
  { turma: "6TA", discLabel: "LÍNGUA INGLESA", professor: "Marise", professorApoio: null, aulas: 2 },
  { turma: "6TA", discLabel: "CIÊNCIAS", professor: "Silmara", professorApoio: null, aulas: 2 },
  { turma: "6TA", discLabel: "ENS.RELIGIOSO", professor: "Marcio", professorApoio: null, aulas: 1 },
  { turma: "6TA", discLabel: "LEI REC. APREND. L. PORT", professor: "Cecilia", professorApoio: "Ivanir", aulas: 2 },
  { turma: "6TA", discLabel: "REC. APREND. MATEMÁTICA", professor: "Andre", professorApoio: "Pedro", aulas: 2 },
  { turma: "6TB", discLabel: "LÍNGUA PORTUGUESA", professor: "Rafael", professorApoio: null, aulas: 4 },
  { turma: "6TB", discLabel: "MATEMÁTICA", professor: "Robson", professorApoio: null, aulas: 4 },
  { turma: "6TB", discLabel: "HISTÓRIA", professor: "Daiane", professorApoio: null, aulas: 2 },
  { turma: "6TB", discLabel: "GEOGRAFIA", professor: "Jackson", professorApoio: null, aulas: 2 },
  { turma: "6TB", discLabel: "ARTE", professor: "Priscila", professorApoio: null, aulas: 2 },
  { turma: "6TB", discLabel: "EDUCAÇÃO FÍSICA", professor: "Elisangela", professorApoio: null, aulas: 2 },
  { turma: "6TB", discLabel: "LÍNGUA INGLESA", professor: "Marise", professorApoio: null, aulas: 2 },
  { turma: "6TB", discLabel: "CIÊNCIAS", professor: "Wellington", professorApoio: null, aulas: 2 },
  { turma: "6TB", discLabel: "ENS.RELIGIOSO", professor: "Janice", professorApoio: null, aulas: 1 },
  { turma: "6TB", discLabel: "LEI REC. APREND. L. PORT", professor: "Cecilia", professorApoio: "Ivanir", aulas: 2 },
  { turma: "6TB", discLabel: "REC. APREND. MATEMÁTICA", professor: "Andre", professorApoio: "Lisiane", aulas: 2 },
  { turma: "6TC", discLabel: "LÍNGUA PORTUGUESA", professor: "Rafael", professorApoio: null, aulas: 4 },
  { turma: "6TC", discLabel: "MATEMÁTICA", professor: "Marcio", professorApoio: null, aulas: 4 },
  { turma: "6TC", discLabel: "HISTÓRIA", professor: "Daiane", professorApoio: null, aulas: 2 },
  { turma: "6TC", discLabel: "GEOGRAFIA", professor: "Jackson", professorApoio: null, aulas: 2 },
  { turma: "6TC", discLabel: "ARTE", professor: "Priscila", professorApoio: null, aulas: 2 },
  { turma: "6TC", discLabel: "EDUCAÇÃO FÍSICA", professor: "Elisangela", professorApoio: null, aulas: 2 },
  { turma: "6TC", discLabel: "LÍNGUA INGLESA", professor: "Marise", professorApoio: null, aulas: 2 },
  { turma: "6TC", discLabel: "CIÊNCIAS", professor: "Wellington", professorApoio: null, aulas: 2 },
  { turma: "6TC", discLabel: "ENS.RELIGIOSO", professor: "Sypriano", professorApoio: null, aulas: 1 },
  { turma: "6TC", discLabel: "LEI REC. APREND. L. PORT", professor: "Cecilia", professorApoio: "Ivanir", aulas: 2 },
  { turma: "6TC", discLabel: "REC. APREND. MATEMÁTICA", professor: "Pedro", professorApoio: "Lisiane", aulas: 2 },
  { turma: "6TD", discLabel: "LÍNGUA PORTUGUESA", professor: "Marta", professorApoio: null, aulas: 4 },
  { turma: "6TD", discLabel: "MATEMÁTICA", professor: "Marcio", professorApoio: null, aulas: 4 },
  { turma: "6TD", discLabel: "HISTÓRIA", professor: "Marcio", professorApoio: null, aulas: 2 },
  { turma: "6TD", discLabel: "GEOGRAFIA", professor: "Ricardo", professorApoio: null, aulas: 2 },
  { turma: "6TD", discLabel: "ARTE", professor: "Priscila", professorApoio: null, aulas: 2 },
  { turma: "6TD", discLabel: "EDUCAÇÃO FÍSICA", professor: "Elisangela", professorApoio: null, aulas: 2 },
  { turma: "6TD", discLabel: "LÍNGUA INGLESA", professor: "Marise", professorApoio: null, aulas: 2 },
  { turma: "6TD", discLabel: "CIÊNCIAS", professor: "Wellington", professorApoio: null, aulas: 2 },
  { turma: "6TD", discLabel: "ENS.RELIGIOSO", professor: "Sypriano", professorApoio: null, aulas: 1 },
  { turma: "6TD", discLabel: "LEI REC. APREND. L. PORT", professor: "Ivanir", professorApoio: "Silmara", aulas: 2 },
  { turma: "6TD", discLabel: "REC. APREND. MATEMÁTICA", professor: "Pedro", professorApoio: "Lisiane", aulas: 2 },
  { turma: "6TE", discLabel: "LÍNGUA PORTUGUESA", professor: "Marta", professorApoio: null, aulas: 4 },
  { turma: "6TE", discLabel: "MATEMÁTICA", professor: "Julio", professorApoio: null, aulas: 4 },
  { turma: "6TE", discLabel: "HISTÓRIA", professor: "Marcio", professorApoio: null, aulas: 2 },
  { turma: "6TE", discLabel: "GEOGRAFIA", professor: "Ricardo", professorApoio: null, aulas: 2 },
  { turma: "6TE", discLabel: "ARTE", professor: "Debora", professorApoio: null, aulas: 2 },
  { turma: "6TE", discLabel: "EDUCAÇÃO FÍSICA", professor: "Marlete", professorApoio: null, aulas: 2 },
  { turma: "6TE", discLabel: "LÍNGUA INGLESA", professor: "Marise", professorApoio: null, aulas: 2 },
  { turma: "6TE", discLabel: "CIÊNCIAS", professor: "Franciele de Assis", professorApoio: null, aulas: 2 },
  { turma: "6TE", discLabel: "ENS.RELIGIOSO", professor: "Sypriano", professorApoio: null, aulas: 1 },
  { turma: "6TE", discLabel: "LEI REC. APREND. L. PORT", professor: "Ivanir", professorApoio: "Silmara", aulas: 2 },
  { turma: "6TE", discLabel: "REC. APREND. MATEMÁTICA", professor: "Pedro", professorApoio: "Lisiane", aulas: 2 },
  { turma: "6TF", discLabel: "LÍNGUA PORTUGUESA", professor: "Marta", professorApoio: null, aulas: 4 },
  { turma: "6TF", discLabel: "MATEMÁTICA", professor: "Matheus", professorApoio: null, aulas: 4 },
  { turma: "6TF", discLabel: "HISTÓRIA", professor: "Robson", professorApoio: null, aulas: 2 },
  { turma: "6TF", discLabel: "GEOGRAFIA", professor: "Ricardo", professorApoio: null, aulas: 2 },
  { turma: "6TF", discLabel: "ARTE", professor: "Debora", professorApoio: null, aulas: 2 },
  { turma: "6TF", discLabel: "EDUCAÇÃO FÍSICA", professor: "Elisangela", professorApoio: null, aulas: 2 },
  { turma: "6TF", discLabel: "LÍNGUA INGLESA", professor: "Marise", professorApoio: null, aulas: 2 },
  { turma: "6TF", discLabel: "CIÊNCIAS", professor: "Wellington", professorApoio: null, aulas: 2 },
  { turma: "6TF", discLabel: "ENS.RELIGIOSO", professor: "Sypriano", professorApoio: null, aulas: 1 },
  { turma: "6TF", discLabel: "LEI REC. APREND. L. PORT", professor: "Ivanir", professorApoio: "Silmara", aulas: 2 },
  { turma: "6TF", discLabel: "REC. APREND. MATEMÁTICA", professor: "Pedro", professorApoio: "Lisiane", aulas: 2 },
  { turma: "6TG", discLabel: "LÍNGUA PORTUGUESA", professor: "Eleciana", professorApoio: null, aulas: 4 },
  { turma: "6TG", discLabel: "MATEMÁTICA", professor: "Matheus", professorApoio: null, aulas: 4 },
  { turma: "6TG", discLabel: "HISTÓRIA", professor: "Robson", professorApoio: null, aulas: 2 },
  { turma: "6TG", discLabel: "GEOGRAFIA", professor: "Ricardo", professorApoio: null, aulas: 2 },
  { turma: "6TG", discLabel: "ARTE", professor: "Debora", professorApoio: null, aulas: 2 },
  { turma: "6TG", discLabel: "EDUCAÇÃO FÍSICA", professor: "Marlete", professorApoio: null, aulas: 2 },
  { turma: "6TG", discLabel: "LÍNGUA INGLESA", professor: "Marise", professorApoio: null, aulas: 2 },
  { turma: "6TG", discLabel: "CIÊNCIAS", professor: "Wellington", professorApoio: null, aulas: 2 },
  { turma: "6TG", discLabel: "ENS.RELIGIOSO", professor: "Sypriano", professorApoio: null, aulas: 1 },
  { turma: "6TG", discLabel: "LEI REC. APREND. L. PORT", professor: "Ivanir", professorApoio: "Silmara", aulas: 2 },
  { turma: "6TG", discLabel: "REC. APREND. MATEMÁTICA", professor: "Pedro", professorApoio: "Lisiane", aulas: 2 },
  { turma: "6TH", discLabel: "LÍNGUA PORTUGUESA", professor: "Marta", professorApoio: null, aulas: 4 },
  { turma: "6TH", discLabel: "MATEMÁTICA", professor: "Matheus", professorApoio: null, aulas: 4 },
  { turma: "6TH", discLabel: "HISTÓRIA", professor: "Wildemberg", professorApoio: null, aulas: 2 },
  { turma: "6TH", discLabel: "GEOGRAFIA", professor: "Ricardo", professorApoio: null, aulas: 2 },
  { turma: "6TH", discLabel: "ARTE", professor: "Debora", professorApoio: null, aulas: 2 },
  { turma: "6TH", discLabel: "EDUCAÇÃO FÍSICA", professor: "Marlete", professorApoio: null, aulas: 2 },
  { turma: "6TH", discLabel: "LÍNGUA INGLESA", professor: "Marise", professorApoio: null, aulas: 2 },
  { turma: "6TH", discLabel: "CIÊNCIAS", professor: "Wellington", professorApoio: null, aulas: 2 },
  { turma: "6TH", discLabel: "ENS.RELIGIOSO", professor: "Sypriano", professorApoio: null, aulas: 1 },
  { turma: "6TH", discLabel: "LEI REC. APREND. L. PORT", professor: "Ivanir", professorApoio: "Silmara", aulas: 2 },
  { turma: "6TH", discLabel: "REC. APREND. MATEMÁTICA", professor: "Gilberto", professorApoio: "Lisiane", aulas: 2 },
  { turma: "6TI", discLabel: "LÍNGUA PORTUGUESA", professor: "Marta", professorApoio: null, aulas: 4 },
  { turma: "6TI", discLabel: "MATEMÁTICA", professor: "Franciele de Assis", professorApoio: null, aulas: 4 },
  { turma: "6TI", discLabel: "HISTÓRIA", professor: "Sarah", professorApoio: null, aulas: 2 },
  { turma: "6TI", discLabel: "GEOGRAFIA", professor: "Ricardo", professorApoio: null, aulas: 2 },
  { turma: "6TI", discLabel: "ARTE", professor: "Debora", professorApoio: null, aulas: 2 },
  { turma: "6TI", discLabel: "EDUCAÇÃO FÍSICA", professor: "Marlete", professorApoio: null, aulas: 2 },
  { turma: "6TI", discLabel: "LÍNGUA INGLESA", professor: "Marise", professorApoio: null, aulas: 2 },
  { turma: "6TI", discLabel: "CIÊNCIAS", professor: "Wellington", professorApoio: null, aulas: 2 },
  { turma: "6TI", discLabel: "ENS.RELIGIOSO", professor: "Sypriano", professorApoio: null, aulas: 1 },
  { turma: "6TI", discLabel: "LEI REC. APREND. L. PORT", professor: "Ivanir", professorApoio: "Silmara", aulas: 2 },
  { turma: "6TI", discLabel: "REC. APREND. MATEMÁTICA", professor: "Gilberto", professorApoio: "Lisiane", aulas: 2 },
  { turma: "7TA", discLabel: "LÍNGUA PORTUGUESA", professor: "Gabriela", professorApoio: null, aulas: 3 },
  { turma: "7TA", discLabel: "MATEMÁTICA", professor: "Andre", professorApoio: null, aulas: 5 },
  { turma: "7TA", discLabel: "HISTÓRIA", professor: "Daiane", professorApoio: null, aulas: 2 },
  { turma: "7TA", discLabel: "GEOGRAFIA", professor: "Dorival", professorApoio: null, aulas: 3 },
  { turma: "7TA", discLabel: "ARTE", professor: "Jordana", professorApoio: null, aulas: 2 },
  { turma: "7TA", discLabel: "EDUCAÇÃO FÍSICA", professor: "Eduardo", professorApoio: null, aulas: 2 },
  { turma: "7TA", discLabel: "LÍNGUA INGLESA", professor: "Herica", professorApoio: null, aulas: 2 },
  { turma: "7TA", discLabel: "CIÊNCIAS", professor: "Eduarda", professorApoio: null, aulas: 3 },
  { turma: "7TA", discLabel: "ENS.RELIGIOSO", professor: "Sypriano", professorApoio: null, aulas: 1 },
  { turma: "7TA", discLabel: "REDAÇÃO E LEITURA", professor: "Robson", professorApoio: null, aulas: 2 },
  { turma: "7TB", discLabel: "LÍNGUA PORTUGUESA", professor: "Gabriela", professorApoio: null, aulas: 3 },
  { turma: "7TB", discLabel: "MATEMÁTICA", professor: "Andre", professorApoio: null, aulas: 5 },
  { turma: "7TB", discLabel: "HISTÓRIA", professor: "Daiane", professorApoio: null, aulas: 2 },
  { turma: "7TB", discLabel: "GEOGRAFIA", professor: "Dorival", professorApoio: null, aulas: 3 },
  { turma: "7TB", discLabel: "ARTE", professor: "Jordana", professorApoio: null, aulas: 2 },
  { turma: "7TB", discLabel: "EDUCAÇÃO FÍSICA", professor: "Eduardo", professorApoio: null, aulas: 2 },
  { turma: "7TB", discLabel: "LÍNGUA INGLESA", professor: "Herica", professorApoio: null, aulas: 2 },
  { turma: "7TB", discLabel: "CIÊNCIAS", professor: "Eduarda", professorApoio: null, aulas: 3 },
  { turma: "7TB", discLabel: "ENS.RELIGIOSO", professor: "Sypriano", professorApoio: null, aulas: 1 },
  { turma: "7TB", discLabel: "REDAÇÃO E LEITURA", professor: "Robson", professorApoio: null, aulas: 2 },
  { turma: "7TC", discLabel: "LÍNGUA PORTUGUESA", professor: "Gabriela", professorApoio: null, aulas: 3 },
  { turma: "7TC", discLabel: "MATEMÁTICA", professor: "Geverson", professorApoio: null, aulas: 5 },
  { turma: "7TC", discLabel: "HISTÓRIA", professor: "Daiane", professorApoio: null, aulas: 2 },
  { turma: "7TC", discLabel: "GEOGRAFIA", professor: "Nelson", professorApoio: null, aulas: 3 },
  { turma: "7TC", discLabel: "ARTE", professor: "Jordana", professorApoio: null, aulas: 2 },
  { turma: "7TC", discLabel: "EDUCAÇÃO FÍSICA", professor: "Eduardo", professorApoio: null, aulas: 2 },
  { turma: "7TC", discLabel: "LÍNGUA INGLESA", professor: "Herica", professorApoio: null, aulas: 2 },
  { turma: "7TC", discLabel: "CIÊNCIAS", professor: "Eleciana", professorApoio: null, aulas: 3 },
  { turma: "7TC", discLabel: "ENS.RELIGIOSO", professor: "Sypriano", professorApoio: null, aulas: 1 },
  { turma: "7TC", discLabel: "REDAÇÃO E LEITURA", professor: "Robson", professorApoio: null, aulas: 2 },
  { turma: "7TD", discLabel: "LÍNGUA PORTUGUESA", professor: "Gabriela", professorApoio: null, aulas: 3 },
  { turma: "7TD", discLabel: "MATEMÁTICA", professor: "Geverson", professorApoio: null, aulas: 5 },
  { turma: "7TD", discLabel: "HISTÓRIA", professor: "Daiane", professorApoio: null, aulas: 2 },
  { turma: "7TD", discLabel: "GEOGRAFIA", professor: "Nelson", professorApoio: null, aulas: 3 },
  { turma: "7TD", discLabel: "ARTE", professor: "Jordana", professorApoio: null, aulas: 2 },
  { turma: "7TD", discLabel: "EDUCAÇÃO FÍSICA", professor: "Eduardo", professorApoio: null, aulas: 2 },
  { turma: "7TD", discLabel: "LÍNGUA INGLESA", professor: "Herica", professorApoio: null, aulas: 2 },
  { turma: "7TD", discLabel: "CIÊNCIAS", professor: "Eleciana", professorApoio: null, aulas: 3 },
  { turma: "7TD", discLabel: "ENS.RELIGIOSO", professor: "Sypriano", professorApoio: null, aulas: 1 },
  { turma: "7TD", discLabel: "REDAÇÃO E LEITURA", professor: "Robson", professorApoio: null, aulas: 2 },
  { turma: "7TE", discLabel: "LÍNGUA PORTUGUESA", professor: "Gabriela", professorApoio: null, aulas: 3 },
  { turma: "7TE", discLabel: "MATEMÁTICA", professor: "Marcio", professorApoio: null, aulas: 5 },
  { turma: "7TE", discLabel: "HISTÓRIA", professor: "Daiane", professorApoio: null, aulas: 2 },
  { turma: "7TE", discLabel: "GEOGRAFIA", professor: "Nelson", professorApoio: null, aulas: 3 },
  { turma: "7TE", discLabel: "ARTE", professor: "Jordana", professorApoio: null, aulas: 2 },
  { turma: "7TE", discLabel: "EDUCAÇÃO FÍSICA", professor: "Eduardo", professorApoio: null, aulas: 2 },
  { turma: "7TE", discLabel: "LÍNGUA INGLESA", professor: "Eliane Rocha", professorApoio: null, aulas: 2 },
  { turma: "7TE", discLabel: "CIÊNCIAS", professor: "Wellington", professorApoio: null, aulas: 3 },
  { turma: "7TE", discLabel: "ENS.RELIGIOSO", professor: "Sypriano", professorApoio: null, aulas: 1 },
  { turma: "7TE", discLabel: "REDAÇÃO E LEITURA", professor: "Rafael", professorApoio: null, aulas: 2 },
  { turma: "7TF", discLabel: "LÍNGUA PORTUGUESA", professor: "Rafael", professorApoio: null, aulas: 3 },
  { turma: "7TF", discLabel: "MATEMÁTICA", professor: "Maristela", professorApoio: null, aulas: 5 },
  { turma: "7TF", discLabel: "HISTÓRIA", professor: "Ednilson", professorApoio: null, aulas: 2 },
  { turma: "7TF", discLabel: "GEOGRAFIA", professor: "Nelson", professorApoio: null, aulas: 3 },
  { turma: "7TF", discLabel: "ARTE", professor: "Lorena", professorApoio: null, aulas: 2 },
  { turma: "7TF", discLabel: "EDUCAÇÃO FÍSICA", professor: "Eduardo", professorApoio: null, aulas: 2 },
  { turma: "7TF", discLabel: "LÍNGUA INGLESA", professor: "Marise", professorApoio: null, aulas: 2 },
  { turma: "7TF", discLabel: "CIÊNCIAS", professor: "Melina", professorApoio: null, aulas: 3 },
  { turma: "7TF", discLabel: "ENS.RELIGIOSO", professor: "Robson", professorApoio: null, aulas: 1 },
  { turma: "7TF", discLabel: "REDAÇÃO E LEITURA", professor: "Rafael", professorApoio: null, aulas: 2 },
  { turma: "7TG", discLabel: "LÍNGUA PORTUGUESA", professor: "Cecilia", professorApoio: null, aulas: 3 },
  { turma: "7TG", discLabel: "MATEMÁTICA", professor: "Maristela", professorApoio: null, aulas: 5 },
  { turma: "7TG", discLabel: "HISTÓRIA", professor: "Ednilson", professorApoio: null, aulas: 2 },
  { turma: "7TG", discLabel: "GEOGRAFIA", professor: "Nelson", professorApoio: null, aulas: 3 },
  { turma: "7TG", discLabel: "ARTE", professor: "Lorena", professorApoio: null, aulas: 2 },
  { turma: "7TG", discLabel: "EDUCAÇÃO FÍSICA", professor: "Heberton", professorApoio: null, aulas: 2 },
  { turma: "7TG", discLabel: "LÍNGUA INGLESA", professor: "Eliane Rocha", professorApoio: null, aulas: 2 },
  { turma: "7TG", discLabel: "CIÊNCIAS", professor: "Melina", professorApoio: null, aulas: 3 },
  { turma: "7TG", discLabel: "ENS.RELIGIOSO", professor: "Robson", professorApoio: null, aulas: 1 },
  { turma: "7TG", discLabel: "REDAÇÃO E LEITURA", professor: "Rafael", professorApoio: null, aulas: 2 },
  { turma: "7TH", discLabel: "LÍNGUA PORTUGUESA", professor: "Patricia", professorApoio: null, aulas: 3 },
  { turma: "7TH", discLabel: "MATEMÁTICA", professor: "Maristela", professorApoio: null, aulas: 5 },
  { turma: "7TH", discLabel: "HISTÓRIA", professor: "Mario", professorApoio: null, aulas: 2 },
  { turma: "7TH", discLabel: "GEOGRAFIA", professor: "Emanuele", professorApoio: null, aulas: 3 },
  { turma: "7TH", discLabel: "ARTE", professor: "Lorena", professorApoio: null, aulas: 2 },
  { turma: "7TH", discLabel: "EDUCAÇÃO FÍSICA", professor: "Heberton", professorApoio: null, aulas: 2 },
  { turma: "7TH", discLabel: "LÍNGUA INGLESA", professor: "Eliane Rocha", professorApoio: null, aulas: 2 },
  { turma: "7TH", discLabel: "CIÊNCIAS", professor: "Melina", professorApoio: null, aulas: 3 },
  { turma: "7TH", discLabel: "ENS.RELIGIOSO", professor: "Marcio", professorApoio: null, aulas: 1 },
  { turma: "7TH", discLabel: "REDAÇÃO E LEITURA", professor: "Robson", professorApoio: null, aulas: 2 },
  { turma: "8TF", discLabel: "LÍNGUA PORTUGUESA", professor: "Antonio Silva", professorApoio: null, aulas: 3 },
  { turma: "8TF", discLabel: "MATEMÁTICA", professor: "Anderson", professorApoio: null, aulas: 4 },
  { turma: "8TF", discLabel: "HISTÓRIA", professor: "Mario", professorApoio: null, aulas: 3 },
  { turma: "8TF", discLabel: "GEOGRAFIA", professor: "Ricardo", professorApoio: null, aulas: 2 },
  { turma: "8TF", discLabel: "ARTE", professor: "Lorena", professorApoio: null, aulas: 2 },
  { turma: "8TF", discLabel: "EDUCAÇÃO FÍSICA", professor: "Eduardo", professorApoio: null, aulas: 2 },
  { turma: "8TF", discLabel: "LÍNGUA INGLESA", professor: "Crislaine", professorApoio: null, aulas: 2 },
  { turma: "8TF", discLabel: "CIÊNCIAS", professor: "Wellington", professorApoio: null, aulas: 3 },
  { turma: "8TF", discLabel: "REDAÇÃO E LEITURA", professor: "Antonio Silva", professorApoio: null, aulas: 2 },
  { turma: "8TF", discLabel: "EDUCAÇÃO DIGITAL", professor: "Gustavo", professorApoio: null, aulas: 2 },
  { turma: "8TG", discLabel: "LÍNGUA PORTUGUESA", professor: "Antonio Silva", professorApoio: null, aulas: 3 },
  { turma: "8TG", discLabel: "MATEMÁTICA", professor: "Franciele de Assis", professorApoio: null, aulas: 4 },
  { turma: "8TG", discLabel: "HISTÓRIA", professor: "Mario", professorApoio: null, aulas: 3 },
  { turma: "8TG", discLabel: "GEOGRAFIA", professor: "Emanuele", professorApoio: null, aulas: 2 },
  { turma: "8TG", discLabel: "ARTE", professor: "Lorena", professorApoio: null, aulas: 2 },
  { turma: "8TG", discLabel: "EDUCAÇÃO FÍSICA", professor: "Eduardo", professorApoio: null, aulas: 2 },
  { turma: "8TG", discLabel: "LÍNGUA INGLESA", professor: "Crislaine", professorApoio: null, aulas: 2 },
  { turma: "8TG", discLabel: "CIÊNCIAS", professor: "Werediana", professorApoio: null, aulas: 3 },
  { turma: "8TG", discLabel: "REDAÇÃO E LEITURA", professor: "Antonio Silva", professorApoio: null, aulas: 2 },
  { turma: "8TG", discLabel: "EDUCAÇÃO DIGITAL", professor: "Paulo", professorApoio: null, aulas: 2 },
  { turma: "8TH", discLabel: "LÍNGUA PORTUGUESA", professor: "Antonio Silva", professorApoio: null, aulas: 3 },
  { turma: "8TH", discLabel: "MATEMÁTICA", professor: "Matheus", professorApoio: null, aulas: 4 },
  { turma: "8TH", discLabel: "HISTÓRIA", professor: "Mario", professorApoio: null, aulas: 3 },
  { turma: "8TH", discLabel: "GEOGRAFIA", professor: "Emanuele", professorApoio: null, aulas: 2 },
  { turma: "8TH", discLabel: "ARTE", professor: "Luciane", professorApoio: null, aulas: 2 },
  { turma: "8TH", discLabel: "EDUCAÇÃO FÍSICA", professor: "Eduardo", professorApoio: null, aulas: 2 },
  { turma: "8TH", discLabel: "LÍNGUA INGLESA", professor: "Crislaine", professorApoio: null, aulas: 2 },
  { turma: "8TH", discLabel: "CIÊNCIAS", professor: "Werediana", professorApoio: null, aulas: 3 },
  { turma: "8TH", discLabel: "REDAÇÃO E LEITURA", professor: "Antonio Silva", professorApoio: null, aulas: 2 },
  { turma: "8TH", discLabel: "EDUCAÇÃO DIGITAL", professor: "Paulo", professorApoio: null, aulas: 2 },
  { turma: "9TG", discLabel: "LÍNGUA PORTUGUESA", professor: "Soneide", professorApoio: null, aulas: 3 },
  { turma: "9TG", discLabel: "MATEMÁTICA", professor: "Franciele de Assis", professorApoio: null, aulas: 5 },
  { turma: "9TG", discLabel: "HISTÓRIA", professor: "Marcio", professorApoio: null, aulas: 2 },
  { turma: "9TG", discLabel: "GEOGRAFIA", professor: "Jackson", professorApoio: null, aulas: 3 },
  { turma: "9TG", discLabel: "ARTE", professor: "Luciane", professorApoio: null, aulas: 2 },
  { turma: "9TG", discLabel: "EDUCAÇÃO FÍSICA", professor: "Cristiane", professorApoio: null, aulas: 2 },
  { turma: "9TG", discLabel: "LÍNGUA INGLESA", professor: "Eliane Rocha", professorApoio: null, aulas: 2 },
  { turma: "9TG", discLabel: "CIÊNCIAS", professor: "Andreia", professorApoio: null, aulas: 2 },
  { turma: "9TG", discLabel: "LEI REC. APREND. L. PORT", professor: "Rafael", professorApoio: null, aulas: 2 },
  { turma: "9TG", discLabel: "REC. APREND. MATEMÁTICA", professor: "Gilberto", professorApoio: "Lisiane", aulas: 2 },
  { turma: "9TH", discLabel: "LÍNGUA PORTUGUESA", professor: "Soneide", professorApoio: null, aulas: 3 },
  { turma: "9TH", discLabel: "MATEMÁTICA", professor: "Julio", professorApoio: null, aulas: 5 },
  { turma: "9TH", discLabel: "HISTÓRIA", professor: "Mario", professorApoio: null, aulas: 2 },
  { turma: "9TH", discLabel: "GEOGRAFIA", professor: "Jackson", professorApoio: null, aulas: 3 },
  { turma: "9TH", discLabel: "ARTE", professor: "Luciane", professorApoio: null, aulas: 2 },
  { turma: "9TH", discLabel: "EDUCAÇÃO FÍSICA", professor: "Cristiane", professorApoio: null, aulas: 2 },
  { turma: "9TH", discLabel: "LÍNGUA INGLESA", professor: "Eliane Rocha", professorApoio: null, aulas: 2 },
  { turma: "9TH", discLabel: "CIÊNCIAS", professor: "Andreia", professorApoio: null, aulas: 2 },
  { turma: "9TH", discLabel: "LEI REC. APREND. L. PORT", professor: "Eduarda", professorApoio: null, aulas: 2 },
  { turma: "9TH", discLabel: "REC. APREND. MATEMÁTICA", professor: "Gilberto", professorApoio: "Lisiane", aulas: 2 },
  { turma: "9TI", discLabel: "LÍNGUA PORTUGUESA", professor: "Eduarda", professorApoio: null, aulas: 3 },
  { turma: "9TI", discLabel: "MATEMÁTICA", professor: "Julio", professorApoio: null, aulas: 5 },
  { turma: "9TI", discLabel: "HISTÓRIA", professor: "Mario", professorApoio: null, aulas: 2 },
  { turma: "9TI", discLabel: "GEOGRAFIA", professor: "Emanuele", professorApoio: null, aulas: 3 },
  { turma: "9TI", discLabel: "ARTE", professor: "Luciane", professorApoio: null, aulas: 2 },
  { turma: "9TI", discLabel: "EDUCAÇÃO FÍSICA", professor: "Cristiane", professorApoio: null, aulas: 2 },
  { turma: "9TI", discLabel: "LÍNGUA INGLESA", professor: "Eduarda", professorApoio: null, aulas: 2 },
  { turma: "9TI", discLabel: "CIÊNCIAS", professor: "Werediana", professorApoio: null, aulas: 2 },
  { turma: "9TI", discLabel: "LEI REC. APREND. L. PORT", professor: "Eduarda", professorApoio: null, aulas: 2 },
  { turma: "9TI", discLabel: "REC. APREND. MATEMÁTICA", professor: "Gilberto", professorApoio: "Lisiane", aulas: 2 },
  { turma: "1NB", discLabel: "LÍNGUA PORTUGUESA", professor: "Ivete", professorApoio: null, aulas: 4 },
  { turma: "1NB", discLabel: "MATEMÁTICA", professor: "Anderson", professorApoio: null, aulas: 4 },
  { turma: "1NB", discLabel: "GEOGRAFIA", professor: "Dorival", professorApoio: null, aulas: 2 },
  { turma: "1NB", discLabel: "BIOLOGIA", professor: "Rodrigo", professorApoio: null, aulas: 2 },
  { turma: "1NB", discLabel: "QUÍMICA", professor: "Viviane", professorApoio: null, aulas: 2 },
  { turma: "1NB", discLabel: "ARTE", professor: "Roberval", professorApoio: null, aulas: 2 },
  { turma: "1NB", discLabel: "EDUCAÇÃO FÍSICA", professor: "Elisangela", professorApoio: null, aulas: 2 },
  { turma: "1NB", discLabel: "LÍNGUA INGLESA", professor: "Eliane", professorApoio: null, aulas: 2 },
  { turma: "1NB", discLabel: "EDUCAÇÃO FINANCEIRA", professor: "Arnaldo", professorApoio: null, aulas: 2 },
  { turma: "1NB", discLabel: "EDUCAÇÃO DIGITAL", professor: "Viviane", professorApoio: null, aulas: 2 },
  { turma: "1NB", discLabel: "HIBRIDA", professor: null, professorApoio: null, aulas: 1 },
  { turma: "2NB", discLabel: "LÍNGUA PORTUGUESA", professor: "Antonio Silva", professorApoio: null, aulas: 4 },
  { turma: "2NB", discLabel: "MATEMÁTICA", professor: "Anderson", professorApoio: null, aulas: 4 },
  { turma: "2NB", discLabel: "HISTÓRIA", professor: "Daiane", professorApoio: null, aulas: 2 },
  { turma: "2NB", discLabel: "FÍSICA", professor: "João Lucas", professorApoio: null, aulas: 2 },
  { turma: "2NB", discLabel: "ARTE", professor: "Roberval", professorApoio: null, aulas: 2 },
  { turma: "2NB", discLabel: "EDUCAÇÃO FÍSICA", professor: "Elisangela", professorApoio: null, aulas: 2 },
  { turma: "2NB", discLabel: "LÍNGUA INGLESA", professor: "Eliane", professorApoio: null, aulas: 2 },
  { turma: "2NB", discLabel: "FILOSOFIA", professor: "Sypriano", professorApoio: null, aulas: 2 },
  { turma: "2NB", discLabel: "SOCIOLOGIA", professor: "Willian", professorApoio: null, aulas: 2 },
  { turma: "2NB", discLabel: "EDUCAÇÃO FINANCEIRA", professor: "Arnaldo", professorApoio: null, aulas: 2 },
  { turma: "2NB", discLabel: "HIBRIDA", professor: null, professorApoio: null, aulas: 1 },
  { turma: "2NC", discLabel: "LÍNGUA PORTUGUESA", professor: "Antonio Silva", professorApoio: null, aulas: 4 },
  { turma: "2NC", discLabel: "MATEMÁTICA", professor: "Carlos", professorApoio: null, aulas: 4 },
  { turma: "2NC", discLabel: "HISTÓRIA", professor: "Daiane", professorApoio: null, aulas: 2 },
  { turma: "2NC", discLabel: "FÍSICA", professor: "João Lucas", professorApoio: null, aulas: 2 },
  { turma: "2NC", discLabel: "ARTE", professor: "Roberval", professorApoio: null, aulas: 2 },
  { turma: "2NC", discLabel: "EDUCAÇÃO FÍSICA", professor: "Elisangela", professorApoio: null, aulas: 2 },
  { turma: "2NC", discLabel: "LÍNGUA INGLESA", professor: "Eliane", professorApoio: null, aulas: 2 },
  { turma: "2NC", discLabel: "FILOSOFIA", professor: "Sypriano", professorApoio: null, aulas: 2 },
  { turma: "2NC", discLabel: "SOCIOLOGIA", professor: "Willian", professorApoio: null, aulas: 2 },
  { turma: "2NC", discLabel: "EDUCAÇÃO FINANCEIRA", professor: "Arnaldo", professorApoio: null, aulas: 2 },
  { turma: "2NC", discLabel: "HIBRIDA", professor: null, professorApoio: null, aulas: 1 },
  { turma: "3NB", discLabel: "LÍNGUA PORTUGUESA", professor: "Antonio Silva", professorApoio: null, aulas: 4 },
  { turma: "3NB", discLabel: "MATEMÁTICA", professor: "Carlos", professorApoio: null, aulas: 3 },
  { turma: "3NB", discLabel: "FÍSICA", professor: "João Lucas", professorApoio: null, aulas: 1 },
  { turma: "3NB", discLabel: "EDUCAÇÃO FÍSICA", professor: "Elisangela", professorApoio: null, aulas: 2 },
  { turma: "3NB", discLabel: "EDUCAÇÃO FINANCEIRA", professor: "Geverson", professorApoio: null, aulas: 1 },
  { turma: "3NB", discLabel: "PROJETO DE VIDA", professor: "Felipe", professorApoio: null, aulas: 1 },
  { turma: "3NB", discLabel: "MATEMÁTICA 2", professor: "Tiago", professorApoio: null, aulas: 1 },
  { turma: "3NB", discLabel: "BIOLOGIA 2", professor: "Cleide", professorApoio: null, aulas: 2 },
  { turma: "3NB", discLabel: "FÍSICA 2", professor: "Viviane", professorApoio: null, aulas: 2 },
  { turma: "3NB", discLabel: "FÍSICA 3", professor: "Viviane", professorApoio: null, aulas: 2 },
  { turma: "3NB", discLabel: "QUÍMICA 1", professor: "Viviane", professorApoio: null, aulas: 2 },
  { turma: "3NB", discLabel: "REC. APREND. L. PORT", professor: "Ivete", professorApoio: null, aulas: 2 },
  { turma: "3NB", discLabel: "REC. APREND. MATEMÁTICA", professor: "Carlos", professorApoio: null, aulas: 2 },
  { turma: "3NC", discLabel: "LÍNGUA PORTUGUESA", professor: "Antonio Silva", professorApoio: null, aulas: 4 },
  { turma: "3NC", discLabel: "MATEMÁTICA", professor: "Carlos", professorApoio: null, aulas: 3 },
  { turma: "3NC", discLabel: "FÍSICA", professor: "João Lucas", professorApoio: null, aulas: 2 },
  { turma: "3NC", discLabel: "EDUCAÇÃO FÍSICA", professor: "Elisangela", professorApoio: null, aulas: 2 },
  { turma: "3NC", discLabel: "LÍNGUA INGLESA", professor: "Eliane", professorApoio: null, aulas: 2 },
  { turma: "3NC", discLabel: "EDUCAÇÃO FINANCEIRA", professor: "Geverson", professorApoio: null, aulas: 1 },
  { turma: "3NC", discLabel: "PROJETO DE VIDA", professor: "Felipe", professorApoio: null, aulas: 1 },
  { turma: "3NC", discLabel: "ARTE 2", professor: "Roberval", professorApoio: null, aulas: 2 },
  { turma: "3NC", discLabel: "GEOGRAFIA 1", professor: "Dorival", professorApoio: null, aulas: 1 },
  { turma: "3NC", discLabel: "HISTÓRIA 1", professor: "Daiane", professorApoio: null, aulas: 1 },
  { turma: "3NC", discLabel: "SOCIOLOGIA 1", professor: "Willian", professorApoio: null, aulas: 2 },
  { turma: "3NC", discLabel: "REC. APREND. L. PORT", professor: "Gleiciane", professorApoio: null, aulas: 2 },
  { turma: "3NC", discLabel: "REC. APREND. MATEMÁTICA", professor: "Carlos", professorApoio: null, aulas: 2 },
  { turma: "1NF ADM", discLabel: "LÍNGUA PORTUGUESA", professor: "Ivete", professorApoio: null, aulas: 2 },
  { turma: "1NF ADM", discLabel: "MATEMÁTICA", professor: "Anderson", professorApoio: null, aulas: 3 },
  { turma: "1NF ADM", discLabel: "GEOGRAFIA", professor: "Dorival", professorApoio: null, aulas: 2 },
  { turma: "1NF ADM", discLabel: "BIOLOGIA", professor: "Rodrigo", professorApoio: null, aulas: 2 },
  { turma: "1NF ADM", discLabel: "QUÍMICA", professor: "Viviane", professorApoio: null, aulas: 2 },
  { turma: "1NF ADM", discLabel: "ARTE", professor: "Roberval", professorApoio: null, aulas: 2 },
  { turma: "1NF ADM", discLabel: "EDUCAÇÃO FÍSICA", professor: "Elisangela", professorApoio: null, aulas: 2 },
  { turma: "1NF ADM", discLabel: "LÍNGUA INGLESA", professor: "Eliane", professorApoio: null, aulas: 2 },
  { turma: "1NF ADM", discLabel: "INFORMÁTICA EMPRESARIAL", professor: "Tiago", professorApoio: null, aulas: 1 },
  { turma: "1NF ADM", discLabel: "PRINCÍPIOS ECONÔMICOS", professor: "Gleiciane", professorApoio: null, aulas: 1 },
  { turma: "1NF ADM", discLabel: "FINANÇAS EMPRESARIAIS", professor: "Felipe", professorApoio: null, aulas: 1 },
  { turma: "1NF ADM", discLabel: "PRINC. DE ADMINISTRAÇÃO", professor: "Tiago", professorApoio: null, aulas: 1 },
  { turma: "1NF ADM", discLabel: "RECURSOS HUMANOS", professor: "Felipe", professorApoio: null, aulas: 1 },
  { turma: "1NF ADM", discLabel: "ESTRATÉGIAS DE MARKETING", professor: "Felipe", professorApoio: null, aulas: 1 },
  { turma: "1NF ADM", discLabel: "TÉCNICAS INTEGRADAS", professor: "Arnaldo", professorApoio: null, aulas: 1 },
  { turma: "1NF ADM", discLabel: "EDUCAÇÃO DIGITAL", professor: "Arnaldo", professorApoio: null, aulas: 1 },
];
async function main() {
  console.log("🌱 Iniciando seed REAL do NexGrade (dados da secretaria)...\n");

  // ------------------------------------------------------------------
  // 1. PLANOS
  // ------------------------------------------------------------------
  const planosExistentes = await db.select().from(planosTable);
  if (planosExistentes.length === 0) {
    await db.insert(planosTable).values([
      { nome: "Gratuito", precoMensal: 0, maxProfessores: 5, maxTurmas: 3, temIA: true, temExport: false, temImport: false, ativo: true },
      { nome: "Pro", precoMensal: 150, maxProfessores: 30, maxTurmas: 20, temIA: true, temExport: true, temImport: true, ativo: true },
      { nome: "Master", precoMensal: 400, maxProfessores: 9999, maxTurmas: 9999, temIA: true, temExport: true, temImport: true, ativo: true },
    ]);
    console.log("✅ Planos criados: Gratuito, Pro, Master");
  } else {
    console.log("⏭️  Planos já existiam — pulado");
  }

  // ------------------------------------------------------------------
  // Limpa dados anteriores da escola_default. Professores, turmas e
  // disciplinas em cascata levam junto professor_disciplinas,
  // turma_disciplinas, horarios e disponibilidade (todas essas tabelas
  // têm onDelete: "cascade" nas FKs pra professoresTable/turmasTable/
  // disciplinasTable) — não precisa apagar cada uma manualmente.
  // ------------------------------------------------------------------
  await db.delete(professoresTable).where(eq(professoresTable.escolaId, ESCOLA_ID));
  await db.delete(turmasTable).where(eq(turmasTable.escolaId, ESCOLA_ID));
  await db.delete(disciplinasTable).where(eq(disciplinasTable.escolaId, ESCOLA_ID));
  await db.delete(salasTable).where(eq(salasTable.escolaId, ESCOLA_ID));
  console.log("🧹 Dados anteriores (professores/turmas/disciplinas/salas) removidos");

  // ------------------------------------------------------------------
  // 2. DISCIPLINAS
  // ------------------------------------------------------------------
  const disciplinasSeed = DISCIPLINAS_REAIS.map((d, i) => ({
    escolaId: ESCOLA_ID,
    nome: d.nome,
    cargaSemanal: 2,
    cor: PALETA_CORES[i % PALETA_CORES.length],
    codigoSae: d.codigoSae,
  }));
  const disciplinasInseridas = await db.insert(disciplinasTable).values(disciplinasSeed).returning();
  const disciplinaIdPorLabel = new Map<string, number>();
  DISCIPLINAS_REAIS.forEach((d, i) => disciplinaIdPorLabel.set(d.label, disciplinasInseridas[i].id));
  const comCodigo = DISCIPLINAS_REAIS.filter((d) => d.codigoSae).length;
  console.log(`✅ ${disciplinasInseridas.length} disciplinas criadas (${comCodigo} com código SAE, ${disciplinasInseridas.length - comCodigo} pendentes de código)`);

  // ------------------------------------------------------------------
  // 3. PROFESSORES
  // ------------------------------------------------------------------
  const professorIdPorNome = new Map<string, number>();
  for (const nome of PROFESSORES_REAIS) {
    const [prof] = await db
      .insert(professoresTable)
      .values({ escolaId: ESCOLA_ID, nome, email: emailFromNome(nome), ativo: true })
      .returning();
    professorIdPorNome.set(nome, prof.id);
  }
  console.log(`✅ ${PROFESSORES_REAIS.length} professores criados (cargaHorariaTotal no padrão de 20h — regime real ainda pendente de confirmação)`);

  // ------------------------------------------------------------------
  // 4. SALAS (genéricas — a escola ainda não confirmou salas reais)
  // ------------------------------------------------------------------
  const salasSeed = [
    { nome: "Sala 01", tipo: "sala_aula", capacidade: 35 },
    { nome: "Sala 02", tipo: "sala_aula", capacidade: 35 },
    { nome: "Sala 03", tipo: "sala_aula", capacidade: 30 },
    { nome: "Laboratório de Informática", tipo: "laboratorio", capacidade: 25 },
    { nome: "Quadra Poliesportiva", tipo: "quadra", capacidade: 40 },
  ].map((s) => ({ ...s, escolaId: ESCOLA_ID }));
  await db.insert(salasTable).values(salasSeed);
  console.log(`✅ ${salasSeed.length} salas genéricas criadas (ajustar quando a escola confirmar salas reais)`);

  // ------------------------------------------------------------------
  // 5. TURMAS
  // ------------------------------------------------------------------
  const turmaIdPorNome = new Map<string, number>();
  for (const t of TURMAS_REAIS) {
    const [turma] = await db
      .insert(turmasTable)
      .values({
        escolaId: ESCOLA_ID,
        nome: t.nome,
        serie: t.serie,
        turno: t.turno,
        nivelEnsino: t.nivelEnsino,
        anoLetivo: 2026,
      })
      .returning();
    turmaIdPorNome.set(t.nome, turma.id);
  }
  console.log(`✅ ${TURMAS_REAIS.length} turmas reais criadas (sem matriz curricular vinculada ainda)`);

  // ------------------------------------------------------------------
  // 6. TURMA_DISCIPLINAS — carga horária real de cada turma+disciplina,
  // com o professor responsável (principal, em caso de co-docência).
  // ------------------------------------------------------------------
  let turmaDisciplinasCriadas = 0;
  let coDocenciaGravadas = 0;
  const profDisciplinaJaVinculado = new Set<string>();
  for (const g of GRADE_REAL) {
    const turmaId = turmaIdPorNome.get(g.turma);
    const disciplinaId = disciplinaIdPorLabel.get(g.discLabel);
    if (!turmaId || !disciplinaId) {
      console.log(`⚠️  Pulei linha da grade sem turma/disciplina resolvida: ${g.turma} / ${g.discLabel}`);
      continue;
    }
    const professorId = g.professor ? professorIdPorNome.get(g.professor) : undefined;
    const professorApoioId = g.professorApoio ? professorIdPorNome.get(g.professorApoio) : undefined;
    if (g.professor && !professorId) {
      console.log(`⚠️  Professor "${g.professor}" não encontrado (turma ${g.turma}, disciplina ${g.discLabel})`);
    }
    if (g.professorApoio && !professorApoioId) {
      console.log(`⚠️  Professor de apoio "${g.professorApoio}" não encontrado (turma ${g.turma}, disciplina ${g.discLabel})`);
    }
    await db.insert(turmaDisciplinasTable).values({
      turmaId,
      disciplinaId,
      professorId: professorId ?? null,
      professorApoioId: professorApoioId ?? null,
      cargaHorariaSemanalOverride: g.aulas,
    });
    turmaDisciplinasCriadas++;
    if (professorApoioId) coDocenciaGravadas++;

    if (professorId) {
      const chave = `${professorId}-${disciplinaId}`;
      if (!profDisciplinaJaVinculado.has(chave)) {
        profDisciplinaJaVinculado.add(chave);
        await db.insert(professorDisciplinasTable).values({ professorId, disciplinaId });
      }
    }
    if (professorApoioId) {
      const chaveApoio = `${professorApoioId}-${disciplinaId}`;
      if (!profDisciplinaJaVinculado.has(chaveApoio)) {
        profDisciplinaJaVinculado.add(chaveApoio);
        await db.insert(professorDisciplinasTable).values({ professorId: professorApoioId, disciplinaId });
      }
    }
  }
  console.log(`✅ ${turmaDisciplinasCriadas} vínculos turma+disciplina criados, com professor e carga horária semanal reais`);
  console.log(`✅ ${coDocenciaGravadas} desses vínculos têm professor de apoio (co-docência real, professorApoioId preenchido)`);
  console.log(`✅ ${profDisciplinaJaVinculado.size} vínculos professor↔disciplina (professor_disciplinas) criados`);


  console.log("\n🎉 Seed real concluído:");
  console.log(`   - ${disciplinasInseridas.length} disciplinas (${comCodigo} com código SAE oficial)`);
  console.log(`   - ${PROFESSORES_REAIS.length} professores reais`);
  console.log(`   - ${TURMAS_REAIS.length} turmas reais (manhã/tarde/noite)`);
  console.log(`   - ${turmaDisciplinasCriadas} combinações turma+disciplina com carga horária e professor`);
  console.log(`   - ${coDocenciaGravadas} aulas de co-docência real gravadas com professorApoioId (as 6 duplas confirmadas: Pedro+Lisiane, Cecília+Ivanir, Ivanir+Silmara, Julio+Juliana, Julio+Matheus, Gilberto+Lisiane)`);
  console.log("\n⚠️  PENDÊNCIAS (ainda não incluídas neste seed):");
  console.log("   - Hora-Atividade obrigatória (disponibilidade_professores) — falta o regime de contrato (20h/40h) de cada professor");
  console.log("   - Grade dia-a-dia (horarios) — rodar o gerador de horário depois deste seed");
  console.log("   - Códigos SAE das disciplinas novas (recomposição da aprendizagem, técnicas, híbrida etc.)\n");

  await pool.end();
}

main().catch((err) => {
  console.error("❌ Erro ao rodar o seed:", err);
  process.exit(1);
});
